import fs from 'fs';
import path from 'path';

// Let's define the comprehensive Oregon venues (105 venues)
const oregonVenues = [
  // Portland - Central & Eastside
  {
    id: "revolution-hall-portland",
    name: "Revolution Hall",
    capacity: 830,
    address: "1300 SE Stark St, Portland, OR 97214",
    city: "Portland",
    genres: ["Indie Rock", "Americana", "Folk", "Comedy", "Pop"],
    contactEmail: "booking@revolutionhall.com",
    contactPhone: "(503) 288-3895",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 830 guests] Iconic former Washington High School auditorium in SE Portland, transformed into a premier concert venue. Features plush theater seating, expansive stage, d&b audiotechnik sound system, and rooftop deck.",
    website: "www.revolutionhall.com"
  },
  {
    id: "doug-fir-lounge-portland",
    name: "Doug Fir Lounge",
    capacity: 299,
    address: "830 E Burnside St, Portland, OR 97214",
    city: "Portland",
    genres: ["Indie Rock", "Folk Rock", "Synthpop", "Singer-Songwriter", "Dream Pop"],
    contactEmail: "booking@dougfirlounge.com",
    contactPhone: "(503) 231-9663",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 299 guests] Celebrated modern log-cabin aesthetic with world-class acoustic design and sound engineering in the basement showroom. Intimate sightlines and artist hospitality lounge.",
    website: "www.dougfirlounge.com"
  },
  {
    id: "mississippi-studios-portland",
    name: "Mississippi Studios",
    capacity: 250,
    address: "3939 N Mississippi Ave, Portland, OR 97227",
    city: "Portland",
    genres: ["Indie Rock", "Americana", "Folk", "Post-Punk", "Acoustic"],
    contactEmail: "booking@mississippistudios.com",
    contactPhone: "(503) 288-3895",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Built by musicians for musicians in a former church. Custom-designed acoustic room with balcony seating, pristine Meyer Sound PA, and Bar Bar patio attached.",
    website: "www.mississippistudios.com"
  },
  {
    id: "wonder-ballroom-portland",
    name: "Wonder Ballroom",
    capacity: 778,
    address: "128 NE Russell St, Portland, OR 97212",
    city: "Portland",
    genres: ["Indie Rock", "Electronic", "Hip-Hop", "Punk", "Metal"],
    contactEmail: "booking@wonderballroom.com",
    contactPhone: "(503) 284-8686",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 778 guests] Historic 1914 Hibernian Hall on NE Russell. Beautiful hardwood floors, Spanish-revival detailing, full lighting rig, and UnderWonder lounge downstairs.",
    website: "www.wonderballroom.com"
  },
  {
    id: "aladdin-theater-portland",
    name: "Aladdin Theater",
    capacity: 620,
    address: "3017 SE Milwaukie Ave, Portland, OR 97202",
    city: "Portland",
    genres: ["Folk", "Rock", "Americana", "World", "Blues"],
    contactEmail: "booking@aladdin-theater.com",
    contactPhone: "(503) 234-9694",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 620 guests] Historic 1928 vaudeville house in the Brooklyn neighborhood. Known for warm natural room tone, tiered theater seating, and Lamp lounge next door.",
    website: "www.aladdin-theater.com"
  },
  {
    id: "holocene-portland",
    name: "Holocene",
    capacity: 320,
    address: "1001 SE Morrison St, Portland, OR 97214",
    city: "Portland",
    genres: ["Electronic", "Synthpop", "Indie Pop", "Experimental", "R&B"],
    contactEmail: "booking@holocene.org",
    contactPhone: "(503) 239-7639",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 320 guests] Converted auto warehouse in the Central Eastside Industrial District. Soaring ceilings, 25-foot projection visuals, stellar sub-bass array, and forward-thinking curation.",
    website: "www.holocene.org"
  },
  {
    id: "the-get-down-portland",
    name: "The Get Down Music Venue",
    capacity: 350,
    address: "614 SE Alder St, Portland, OR 97214",
    city: "Portland",
    genres: ["Funk", "Jam Band", "Soul", "Reggae", "Electronic"],
    contactEmail: "booking@thegetdownpdx.com",
    contactPhone: "(503) 893-5590",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] Purpose-built live music room with premium acoustic treatment, Danley sound system, immersive stage lighting, and a spacious sprung oak dance floor.",
    website: "www.thegetdownpdx.com"
  },
  {
    id: "polaris-hall-portland",
    name: "Polaris Hall",
    capacity: 220,
    address: "635 N Killingsworth Ct, Portland, OR 97217",
    city: "Portland",
    genres: ["Indie Folk", "Chamber Pop", "Jazz", "Americana", "Acoustic"],
    contactEmail: "booking@polarishall.com",
    contactPhone: "(503) 288-3895",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Historic 1930s Masonic hall in North Portland with ballroom fir floors, vaulted curved ceiling, pristine acoustic dampening, and full bar.",
    website: "www.polarishall.com"
  },
  {
    id: "dantes-portland",
    name: "Dante's",
    capacity: 350,
    address: "350 W Burnside St, Portland, OR 97209",
    city: "Portland",
    genres: ["Punk", "Hard Rock", "Garage Rock", "Metal", "Cabaret"],
    contactEmail: "booking@danteslive.com",
    contactPhone: "(866) 777-8932",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] Legendary downtown Portland rock sanctuary with fiery stage show pedigree, infamous Sinferno cabaret, loud sound system, and late-night pizza counter.",
    website: "www.danteslive.com"
  },
  {
    id: "star-theater-portland",
    name: "Star Theater",
    capacity: 450,
    address: "13 NW 6th Ave, Portland, OR 97209",
    city: "Portland",
    genres: ["Indie Rock", "Post-Punk", "Darkwave", "Electronic", "Hard Rock"],
    contactEmail: "booking@startheaterportland.com",
    contactPhone: "(503) 248-4700",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 450 guests] Historic 1911 silent cinema in Old Town Chinatown transformed into a multi-tier concert venue with pro stage, high ceilings, and outdoor deck.",
    website: "www.startheaterportland.com"
  },
  {
    id: "white-eagle-saloon-portland",
    name: "McMenamins White Eagle Saloon",
    capacity: 120,
    address: "836 N Russell St, Portland, OR 97227",
    city: "Portland",
    genres: ["Blues", "Americana", "Folk Rock", "Roots", "Bluegrass"],
    contactEmail: "whiteeaglebooking@mcmenamins.com",
    contactPhone: "(503) 282-6810",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Historic 1905 Polish railroad tavern and rock haven in North Portland. Intimate stage, vintage stained glass, heated patio, and artist rooms upstairs.",
    website: "www.mcmenamins.com/white-eagle"
  },
  {
    id: "laurelthirst-pub-portland",
    name: "LaurelThirst Public House",
    capacity: 130,
    address: "2958 NE Glisan St, Portland, OR 97232",
    city: "Portland",
    genres: ["Americana", "Bluegrass", "Folk", "Country", "Roots"],
    contactEmail: "booking@laurelthirst.com",
    contactPhone: "(503) 232-1504",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Portland's oldest continuously running original music pub (since 1988). Dedicated to roots, bluegrass, and folk with early happy hour and prime evening sets.",
    website: "www.laurelthirst.com"
  },
  {
    id: "landmark-saloon-portland",
    name: "The Landmark Saloon",
    capacity: 140,
    address: "4847 SE Division St, Portland, OR 97206",
    city: "Portland",
    genres: ["Honky Tonk", "Outlaw Country", "Americana", "Bluegrass"],
    contactEmail: "booking@landmarksaloon.com",
    contactPhone: "(503) 894-8132",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Authentic 1900s farmhouse converted into a honky-tonk saloon on SE Division. Huge outdoor yard with secondary stage, cornhole, and horseshoe pits.",
    website: "www.landmarksaloon.com"
  },
  {
    id: "black-water-bar-portland",
    name: "Black Water Bar",
    capacity: 150,
    address: "835 NE Broadway, Portland, OR 97232",
    city: "Portland",
    genres: ["Punk", "Hardcore", "Crust", "Metal", "All-Ages"],
    contactEmail: "blackwaterportland@gmail.com",
    contactPhone: "(503) 281-0439",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] DIY vegan punk rock clubhouse and record store. Known for heavy PA subwoofers, strictly inclusive DIY booking, and legendary vegan burgers.",
    website: "www.facebook.com/blackwaterportland"
  },
  {
    id: "manor-house-portland",
    name: "The Manor House (Jack London Revue)",
    capacity: 220,
    address: "529 SW 4th Ave, Portland, OR 97204",
    city: "Portland",
    genres: ["Jazz", "Funk", "Soul", "Neo-Soul", "Blues"],
    contactEmail: "booking@jacklondonrevue.com",
    contactPhone: "(503) 384-2347",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Subterranean speakeasy jazz club beneath the Rialto Poolroom downtown. Features velvet booths, custom sound system, baby grand piano, and artisan cocktails.",
    website: "www.jacklondonrevue.com"
  },
  {
    id: "the-coffin-club-portland",
    name: "The Coffin Club",
    capacity: 250,
    address: "421 SE Grand Ave, Portland, OR 97214",
    city: "Portland",
    genres: ["Goth", "Darkwave", "Post-Punk", "Industrial", "Synthwave"],
    contactEmail: "booking@thecoffinclubpdx.com",
    contactPhone: "(503) 236-4108",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Renowned gothic horror-themed nightclub with custom coffin decor, dual dance spaces, live stage, and welcoming dark alternative community.",
    website: "www.thecoffinclubpdx.com"
  },
  {
    id: "kelly-olympian-portland",
    name: "Kelly's Olympian",
    capacity: 135,
    address: "426 SW Washington St, Portland, OR 97204",
    city: "Portland",
    genres: ["Garage Rock", "Indie Rock", "Psych", "Punk", "Hip-Hop"],
    contactEmail: "booking@kellysolympian.com",
    contactPhone: "(503) 228-3669",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 135 guests] Portland's third-oldest continuously operating bar (established 1902). Features vintage neon signs, antique motorcycles hanging from ceilings, and backroom stage.",
    website: "www.kellysolympian.com"
  },
  {
    id: "the-big-legrowlski-portland",
    name: "The Big Legrowlski",
    capacity: 140,
    address: "812 NW Couch St, Portland, OR 97209",
    city: "Portland",
    genres: ["Funk", "Jam Band", "Psychedelic", "Indie", "Jazz"],
    contactEmail: "booking@biglegrowlski.com",
    contactPhone: "(503) 206-6481",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Pearl District craft taproom and music hub themed around 'The Big Lebowski'. Features daily live jam sessions, touring funk bands, and heated sidewalk patio.",
    website: "www.biglegrowlski.com"
  },
  {
    id: "show-bar-revolution-hall-portland",
    name: "Show Bar at Revolution Hall",
    capacity: 120,
    address: "1300 SE Stark St #101, Portland, OR 97214",
    city: "Portland",
    genres: ["Acoustic", "Indie", "Folk", "Jazz", "Comedy"],
    contactEmail: "showbar@revolutionhall.com",
    contactPhone: "(503) 288-3895",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Ground-floor bar inside Revolution Hall with dedicated intimate stage, full craft cocktail program, and booth seating for acoustic touring sets.",
    website: "www.revolutionhall.com/show-bar"
  },
  {
    id: "crystal-ballroom-portland",
    name: "McMenamins Crystal Ballroom",
    capacity: 1500,
    address: "1332 W Burnside St, Portland, OR 97209",
    city: "Portland",
    genres: ["Rock", "Alternative", "Hip-Hop", "Indie", "Pop"],
    contactEmail: "booking@mcmenamins.com",
    contactPhone: "(503) 225-0047",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1500 guests] Legendary 1914 third-story ballroom in downtown Portland famous for its mechanical 'floating' wooden dance floor, grand crystal chandeliers, and murals.",
    website: "www.crystalballroompdx.com"
  },
  {
    id: "lolas-room-portland",
    name: "Lola's Room at the Crystal Ballroom",
    capacity: 250,
    address: "1332 W Burnside St 2nd Floor, Portland, OR 97209",
    city: "Portland",
    genres: ["Indie Rock", "Pop-Punk", "Electronic", "Tribute"],
    contactEmail: "booking@mcmenamins.com",
    contactPhone: "(503) 225-0047",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Second-floor mid-size venue inside the historic Crystal Ballroom building with sprung hardwood floor, full bar, and touring band dressing rooms.",
    website: "www.crystalballroompdx.com/lolas-room"
  },
  {
    id: "alberta-abbey-portland",
    name: "Alberta Abbey",
    capacity: 400,
    address: "126 NE Alberta St, Portland, OR 97211",
    city: "Portland",
    genres: ["Soul", "Gospel", "Jazz", "R&B", "Indie Rock"],
    contactEmail: "booking@albertaabbey.org",
    contactPhone: "(503) 505-7288",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 400 guests] Historic 1920s brick church in the Alberta Arts District transformed into a community arts center with grand auditorium and basement cafe stage.",
    website: "www.albertaabbey.org"
  },
  {
    id: "turn-turn-turn-portland",
    name: "Turn! Turn! Turn!",
    capacity: 110,
    address: "8 NE Killingsworth St, Portland, OR 97211",
    city: "Portland",
    genres: ["Folk", "Garage Rock", "Experimental", "Psych", "Indie"],
    contactEmail: "turnturnturnpdx@gmail.com",
    contactPhone: "(503) 284-6019",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 110 guests] Hybrid vintage record/book store and neighborhood bar on Killingsworth hosting eclectic indie and underground folk tours.",
    website: "www.turnturnturnpdx.com"
  },
  {
    id: "the-fixin-to-portland",
    name: "The Fixin' To",
    capacity: 140,
    address: "8218 N Lombard St, Portland, OR 97203",
    city: "Portland",
    genres: ["Punk", "Garage Rock", "Country", "Americana", "Indie"],
    contactEmail: "booking@thefixinto.com",
    contactPhone: "(503) 477-4995",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] St. Johns neighborhood music joint with Southern honky-tonk vibe, pie case, expansive back patio, and loud backroom stage.",
    website: "www.thefixinto.com"
  },
  {
    id: "the-1905-portland",
    name: "The 1905",
    capacity: 90,
    address: "830 N Shaver St, Portland, OR 97227",
    city: "Portland",
    genres: ["Jazz", "Bebop", "Hard Bop", "Latin Jazz"],
    contactEmail: "music@the1905.org",
    contactPhone: "(503) 460-7005",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 90 guests] World-renowned dedicated jazz listening room serving artisan pizza and Italian wines with acoustic grand piano and two showtimes nightly.",
    website: "www.the1905.org"
  },
  {
    id: "hawthorne-theatre-portland",
    name: "Hawthorne Theatre",
    capacity: 550,
    address: "1507 SE 39th Ave, Portland, OR 97214",
    city: "Portland",
    genres: ["Metal", "Hardcore", "Punk", "Emo", "Hip-Hop", "All-Ages"],
    contactEmail: "booking@hawthornetheatre.com",
    contactPhone: "(503) 233-7100",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 550 guests] Premier historic concert room on SE Hawthorne Blvd featuring major national heavy rock tours, alongside the 150-cap Hawthorne Lounge.",
    website: "www.hawthornetheatre.com"
  },
  {
    id: "manor-saloon-portland",
    name: "The Secret Society Ballroom",
    capacity: 220,
    address: "116 NE Russell St, Portland, OR 97212",
    city: "Portland",
    genres: ["Jazz", "Swing", "Cabaret", "Folk", "Soul"],
    contactEmail: "booking@secretsocietyballroom.com",
    contactPhone: "(503) 493-3600",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Vintage 1907 Victorian ballroom with arched timber ceiling, vintage wooden bar, and acoustic resonance ideal for swing, roots, and chamber ensembles.",
    website: "www.secretsocietyballroom.com"
  },
  {
    id: "bunk-bar-water-portland",
    name: "Bunk Bar Water Ave",
    capacity: 180,
    address: "1028 SE Water Ave, Portland, OR 97214",
    city: "Portland",
    genres: ["Indie Rock", "Garage Rock", "Punk", "Americana"],
    contactEmail: "music@bunksandwiches.com",
    contactPhone: "(503) 328-2865",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Central Eastside industrial sandwich joint by day, buzzing rock club by night. Raised corner stage, outdoor picnic benches, and craft draft beer.",
    website: "www.bunkbar.com"
  },
  {
    id: "goodfoot-lounge-portland",
    name: "The Goodfoot Lounge",
    capacity: 180,
    address: "2845 SE Stark St, Portland, OR 97214",
    city: "Portland",
    genres: ["Funk", "Soul", "Jam Band", "Afrobeat", "Jazz"],
    contactEmail: "music@thegoodfoot.com",
    contactPhone: "(503) 239-9292",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Beloved two-level music venue in SE Portland. Upstairs art gallery and pool hall; downstairs sunken dance floor and stage with legendary weekly funk/soul residencies.",
    website: "www.thegoodfoot.com"
  },
  {
    id: "twilight-cafe-bar-portland",
    name: "Twilight Cafe & Bar",
    capacity: 120,
    address: "1420 SE Powell Blvd, Portland, OR 97202",
    city: "Portland",
    genres: ["Punk", "Metal", "Hardcore", "Stoner Rock"],
    contactEmail: "twilightcafebar@gmail.com",
    contactPhone: "(503) 234-7067",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Eastside punk and heavy underground music dive on Powell Blvd with high energy shows, great bar staff, and welcoming touring hospitality.",
    website: "www.twilightcafebar.com"
  },

  // Eugene & Willamette Valley
  {
    id: "mcdonald-theatre-eugene",
    name: "McDonald Theatre",
    capacity: 1000,
    address: "1010 Willamette St, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Rock", "Electronic", "Hip-Hop", "Indie", "Reggae", "Bluegrass"],
    contactEmail: "booking@mcdonaldtheatre.com",
    contactPhone: "(541) 345-4442",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1000 guests] Historic 1925 Art Deco palace in downtown Eugene. Converted into the city's foremost general admission concert venue with grand proscenium and wraparound balcony.",
    website: "www.mcdonaldtheatre.com"
  },
  {
    id: "wow-hall-eugene",
    name: "WOW Hall (Community Center for the Performing Arts)",
    capacity: 400,
    address: "291 W 8th Ave, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Indie Rock", "Punk", "Folk", "World", "All-Ages", "Electronic"],
    contactEmail: "booking@wowhall.org",
    contactPhone: "(541) 687-2746",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 400 guests] Historic 1932 Woodmen of the World hall, operating as an all-ages non-profit arts center since 1975. Features sprung hard-rock maple dance floor and storied music history.",
    website: "www.wowhall.org"
  },
  {
    id: "john-henrys-eugene",
    name: "John Henry's",
    capacity: 275,
    address: "77 W 8th Ave, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Punk", "Indie Rock", "Metal", "Funk", "Dance"],
    contactEmail: "booking@johnhenryseugene.com",
    contactPhone: "(541) 505-8968",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 275 guests] Downtown Eugene's beloved high-energy rock venue with raised proscenium stage, arcade bar area, outdoor patio, and nightly touring bands.",
    website: "www.johnhenryseugene.com"
  },
  {
    id: "sam-bonds-garage-eugene",
    name: "Sam Bond's Garage",
    capacity: 150,
    address: "407 Blair Blvd, Eugene, OR 97402",
    city: "Eugene",
    genres: ["Bluegrass", "Folk", "Americana", "Indie Rock", "Funk"],
    contactEmail: "sambondsbooking@gmail.com",
    contactPhone: "(541) 431-6603",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] The beating cultural heart of Eugene's historic Whiteaker neighborhood. Serving local ales, pub food, and hosting live roots and indie music 7 nights a week.",
    website: "www.sambonds.com"
  },
  {
    id: "big-dirty-eugene",
    name: "The Big Dirty",
    capacity: 250,
    address: "282 E 8th Ave, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Electronic", "Funk", "Hip-Hop", "Jam Band", "Bass"],
    contactEmail: "booking@thebigdirty.live",
    contactPhone: "(541) 636-3999",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Modern downtown Eugene live music lounge featuring Funktion-One sound system, projection mapping, custom LED arrays, and VIP booth seating.",
    website: "www.thebigdirty.live"
  },
  {
    id: "hult-center-soreng-eugene",
    name: "Hult Center - Soreng Theater",
    capacity: 498,
    address: "1 Eugene Center, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Jazz", "Acoustic", "Classical", "World", "Folk"],
    contactEmail: "hultbox@eugene-or.gov",
    contactPhone: "(541) 682-5000",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 498 guests] Intimate, acoustically engineered proscenium theater inside Eugene's flagship performing arts complex. Perfect for touring acoustic and jazz artists.",
    website: "www.hultcenter.org"
  },
  {
    id: "whirled-pies-eugene",
    name: "Whirled Pies Downtown Stage",
    capacity: 220,
    address: "199 W 8th Ave, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Americana", "Blues", "Rock", "World", "All-Ages"],
    contactEmail: "booking@whirledpies.com",
    contactPhone: "(541) 636-3280",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Spacious community-oriented pizzeria and live venue with large raised stage, family-friendly all-ages floor, and local microbrew taps.",
    website: "www.whirledpies.com"
  },
  {
    id: "old-nick-pub-eugene",
    name: "Old Nick's Pub",
    capacity: 130,
    address: "211 Washington St, Eugene, OR 97401",
    city: "Eugene",
    genres: ["Metal", "Punk", "Goth", "Darkwave", "Folk"],
    contactEmail: "oldnickspub@gmail.com",
    contactPhone: "(541) 654-4447",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Historic 1890s pub in the Whiteaker neighborhood catering to alternative, heavy metal, gothic, and folk music with outdoor garden stage.",
    website: "www.oldnickspub.com"
  },
  {
    id: "oakshire-public-house-eugene",
    name: "Oakshire Public House Stage",
    capacity: 180,
    address: "207 Madison St, Eugene, OR 97402",
    city: "Eugene",
    genres: ["Bluegrass", "Americana", "Indie Folk", "Acoustic"],
    contactEmail: "music@oakbrew.com",
    contactPhone: "(541) 654-0164",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Whiteaker craft brewery taproom and patio with regular live acoustic, bluegrass jams, and visiting touring musicians.",
    website: "www.oakbrew.com"
  },

  // Bend & Central Oregon
  {
    id: "domino-room-bend",
    name: "The Domino Room",
    capacity: 450,
    address: "51 NW Greenwood Ave, Bend, OR 97701",
    city: "Bend",
    genres: ["Rock", "Metal", "Punk", "Hip-Hop", "Reggae", "Indie"],
    contactEmail: "booking@midtownballroom.com",
    contactPhone: "(541) 388-1106",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 450 guests] Central Oregon's landmark independent rock club in the Midtown Complex. Features two levels, loud tour PA, and dedicated touring band accommodations.",
    website: "www.midtownballroom.com/domino-room"
  },
  {
    id: "midtown-ballroom-bend",
    name: "Midtown Ballroom",
    capacity: 1000,
    address: "51 NW Greenwood Ave, Bend, OR 97701",
    city: "Bend",
    genres: ["Electronic", "Rock", "Jam Band", "Hip-Hop", "Country"],
    contactEmail: "booking@midtownballroom.com",
    contactPhone: "(541) 388-1106",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1000 guests] Bend's largest indoor music venue. Outfitted with high-output touring concert sound, expansive stage, full bar, and green room suites.",
    website: "www.midtownballroom.com"
  },
  {
    id: "volcanic-theatre-pub-bend",
    name: "Volcanic Theatre Pub",
    capacity: 220,
    address: "70 SW Century Dr, Bend, OR 97702",
    city: "Bend",
    genres: ["Indie Rock", "Americana", "Funk", "Punk", "Bluegrass"],
    contactEmail: "booking@volcanictheatrepub.com",
    contactPhone: "(541) 323-1881",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Intimate arts hub in Bend's Old Mill District. Furnished with vintage theater seats and velvet sofas, craft brews, top tier acoustics, and welcoming staff.",
    website: "www.volcanictheatrepub.com"
  },
  {
    id: "silver-moon-brewing-bend",
    name: "Silver Moon Brewing Taproom & Stage",
    capacity: 300,
    address: "24 NW Greenwood Ave, Bend, OR 97701",
    city: "Bend",
    genres: ["Americana", "Funk", "Rock", "Bluegrass", "Cover Bands"],
    contactEmail: "music@silvermoonbrewing.com",
    contactPhone: "(541) 388-8331",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 300 guests] Bend's oldest craft brewery with large indoor concert room and massive heated outdoor beer garden stage hosting touring artists year-round.",
    website: "www.silvermoonbrewing.com"
  },
  {
    id: "tower-theatre-bend",
    name: "Tower Theatre",
    capacity: 460,
    address: "835 NW Wall St, Bend, OR 97703",
    city: "Bend",
    genres: ["Classical", "Jazz", "Folk", "Americana", "Theatre"],
    contactEmail: "info@towertheatre.org",
    contactPhone: "(541) 317-0700",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 460 guests] Historic 1940 Art Deco landmark in downtown Bend. Meticulously restored with world-class acoustics, fly loft, and full theatrical production gear.",
    website: "www.towertheatre.org"
  },
  {
    id: "general-duffys-redmond",
    name: "General Duffy's Waterhole & Annex",
    capacity: 400,
    address: "404 SW Forest Ave, Redmond, OR 97756",
    city: "Redmond",
    genres: ["Country", "Southern Rock", "Americana", "Blues"],
    contactEmail: "events@generalduffys.com",
    contactPhone: "(541) 527-4345",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 400 guests] Premier Central Oregon gathering place in Redmond featuring indoor live music stage and covered outdoor concert plaza surrounded by food trucks.",
    website: "www.generalduffys.com"
  },
  {
    id: "the-belfry-sisters",
    name: "The Belfry",
    capacity: 180,
    address: "302 E Main Ave, Sisters, OR 97759",
    city: "Sisters",
    genres: ["Americana", "Bluegrass", "Folk", "Indie Rock", "Acoustic"],
    contactEmail: "belfryevents@gmail.com",
    contactPhone: "(541) 815-9122",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Beautifully renovated 1910 church in western-themed Sisters, Oregon. High cedar vaulted ceilings, warm acoustic envelope, and regular touring roots acts.",
    website: "www.belfryevents.com"
  },
  {
    id: "hub-city-pub-albany",
    name: "The Garage Bar & Grill",
    capacity: 160,
    address: "313 1st Ave E, Albany, OR 97321",
    city: "Albany",
    genres: ["Rock", "Country", "Blues", "Americana"],
    contactEmail: "thegaragealbany@gmail.com",
    contactPhone: "(541) 926-8988",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 160 guests] Downtown historic Albany live music bar featuring classic rock, blues, and country bands on the Willamette River corridor.",
    website: "www.facebook.com/thegaragealbany"
  },
  {
    id: "calapooia-brewing-albany",
    name: "Calapooia Brewing Taproom & Stage",
    capacity: 140,
    address: "140 Hill St NE, Albany, OR 97321",
    city: "Albany",
    genres: ["Blues", "Bluegrass", "Folk", "Americana"],
    contactEmail: "info@calapooiabrewing.com",
    contactPhone: "(541) 928-7931",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Historic brick warehouse brewery in Albany offering local ales, smash burgers, and weekend live bluegrass/blues sets.",
    website: "www.calapooiabrewing.com"
  },

  // Corvallis & Benton County
  {
    id: "whiteside-theatre-corvallis",
    name: "Whiteside Theatre",
    capacity: 800,
    address: "361 SW Madison Ave, Corvallis, OR 97333",
    city: "Corvallis",
    genres: ["Classic Rock", "Indie", "Folk", "Americana", "Film"],
    contactEmail: "booking@whitesidetheatre.org",
    contactPhone: "(541) 752-0431",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 800 guests] Magnificent 1922 Italian Renaissance movie palace in downtown Corvallis with grand balcony, proscenium stage, and modern digital sound system.",
    website: "www.whitesidetheatre.org"
  },
  {
    id: "bombs-away-cafe-corvallis",
    name: "Bombs Away Cafe",
    capacity: 150,
    address: "2527 NW Monroe Ave, Corvallis, OR 97330",
    city: "Corvallis",
    genres: ["Indie Rock", "Punk", "Funk", "Folk", "Reggae"],
    contactEmail: "bombsawaybooking@gmail.com",
    contactPhone: "(541) 757-7769",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Long-running music cafe on Monroe right across from Oregon State University. Southwestern kitchen, draft microbrews, and high-energy college rock shows.",
    website: "www.bombsawaycafe.com"
  },
  {
    id: "old-world-deli-corvallis",
    name: "Old World Center / Oregon Trail Brewery",
    capacity: 130,
    address: "341 SW 2nd St, Corvallis, OR 97333",
    city: "Corvallis",
    genres: ["Jazz", "Acoustic", "Blues", "Americana", "Bluegrass"],
    contactEmail: "oldworlddelicorvallis@gmail.com",
    contactPhone: "(541) 752-8549",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Historic 1970s timber-framed deli and taproom in downtown Corvallis featuring live acoustic music and jazz residencies.",
    website: "www.oldworldcenter.com"
  },

  // Salem & Marion County
  {
    id: "historic-elsinore-theatre-salem",
    name: "Historic Elsinore Theatre",
    capacity: 1290,
    address: "170 High St SE, Salem, OR 97301",
    city: "Salem",
    genres: ["Rock", "Classical", "Folk", "Tribute", "Jazz"],
    contactEmail: "info@elsinoretheatre.com",
    contactPhone: "(503) 375-3574",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1290 guests] Majestic 1926 Tudor Gothic movie and concert palace with soaring stained glass windows, Mighty Wurlitzer pipe organ, and national tour production specs.",
    website: "www.elsinoretheatre.com"
  },
  {
    id: "infinity-room-salem",
    name: "The Infinity Room",
    capacity: 120,
    address: "210 Liberty St SE #150, Salem, OR 97301",
    city: "Salem",
    genres: ["Indie Rock", "Comedy", "Punk", "Acoustic", "All-Ages"],
    contactEmail: "infinityroomsalem@gmail.com",
    contactPhone: "(503) 395-5162",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Dedicated all-ages comedy and indie music club in downtown Salem with full vegan restaurant, craft cocktails, and stage sound.",
    website: "www.infinityroomsalem.com"
  },
  {
    id: "the-bad-space-salem",
    name: "The Bad Space",
    capacity: 100,
    address: "140 Liberty St NE, Salem, OR 97301",
    city: "Salem",
    genres: ["Punk", "Hardcore", "Metal", "Noise", "All-Ages"],
    contactEmail: "thebadspacesalem@gmail.com",
    contactPhone: "(503) 485-9922",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 100 guests] Salem underground DIY music venue dedicated to all-ages heavy, hardcore, and indie rock touring bands.",
    website: "www.thebadspacesalem.com"
  },
  {
    id: "half-penny-salem",
    name: "Half Penny Public House",
    capacity: 160,
    address: "3743 Commercial St SE, Salem, OR 97302",
    city: "Salem",
    genres: ["Classic Rock", "Blues", "Americana", "Country"],
    contactEmail: "halfpennysalem@gmail.com",
    contactPhone: "(503) 540-5899",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 160 guests] South Salem Irish tavern with large stage, raised dance floor, hearty pub cuisine, and lively weekend live music.",
    website: "www.halfpennypub.com"
  },

  // Southern Oregon (Ashland, Medford, Grants Pass, Jacksonville, Klamath Falls)
  {
    id: "historic-ashland-armory",
    name: "Historic Ashland Armory",
    capacity: 700,
    address: "208 Oak St, Ashland, OR 97520",
    city: "Ashland",
    genres: ["Electronic", "Rock", "Reggae", "Funk", "Jam Band"],
    contactEmail: "booking@liveatthearmory.com",
    contactPhone: "(541) 482-1271",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 700 guests] 1912 stone fortress turned premier southern Oregon concert hall. Features towering ceilings, spring-loaded hardwood floor, high-end sound and lights.",
    website: "www.liveatthearmory.com"
  },
  {
    id: "havurah-shir-hadash-ashland",
    name: "The Havurah Sanctuary Hall",
    capacity: 200,
    address: "185 N Mountain Ave, Ashland, OR 97520",
    city: "Ashland",
    genres: ["Acoustic", "Folk", "World", "Chamber", "Classical"],
    contactEmail: "music@havurahshirhadash.org",
    contactPhone: "(541) 488-7716",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] Beautiful timber-framed sanctuary in Ashland renowned for crystal-clear natural acoustics and intimate candlelit acoustic tour showcases.",
    website: "www.havurahshirhadash.org"
  },
  {
    id: "the-holly-theatre-medford",
    name: "Holly Theatre",
    capacity: 1000,
    address: "226 W 6th St, Medford, OR 97501",
    city: "Medford",
    genres: ["Rock", "Americana", "Classical", "Pop", "Country"],
    contactEmail: "booking@hollytheatre.org",
    contactPhone: "(541) 772-3797",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1000 guests] Historic 1930 Spanish-Venetian palace in downtown Medford, restored as southern Oregon's premier indoor concert theater.",
    website: "www.hollytheatre.org"
  },
  {
    id: "johnny-b-medford",
    name: "Johnny B's Rockin' Diner",
    capacity: 120,
    address: "120 E 6th St, Medford, OR 97501",
    city: "Medford",
    genres: ["Punk", "Metal", "Hard Rock", "Garage Rock", "Indie"],
    contactEmail: "johnnybsmedford@gmail.com",
    contactPhone: "(541) 773-1900",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Cult-favorite Medford punk dive with burger diner in front, loud live stage in back, pinball, and essential I-5 tour stop hospitality.",
    website: "www.facebook.com/johnnybsmedford"
  },
  {
    id: "the-sound-lounge-grants-pass",
    name: "The Sound Lounge",
    capacity: 180,
    address: "225 SE H St, Grants Pass, OR 97526",
    city: "Grants Pass",
    genres: ["Rock", "Blues", "Funk", "Reggae", "Americana"],
    contactEmail: "thesoundloungegp@gmail.com",
    contactPhone: "(541) 479-0712",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Grants Pass premier live music lounge featuring dedicated concert sound, dance floor, full cocktail bar, and outdoor smoking patio.",
    website: "www.thesoundloungegp.com"
  },
  {
    id: "rogue-theatre-grants-pass",
    name: "Historic Rogue Theatre",
    capacity: 500,
    address: "143 SE H St, Grants Pass, OR 97526",
    city: "Grants Pass",
    genres: ["Rock", "Folk", "Americana", "Blues", "Comedy"],
    contactEmail: "booking@roguetheatre.org",
    contactPhone: "(541) 471-1316",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 500 guests] 1938 Art Deco theater in downtown Grants Pass hosting national touring musicians with professional acoustic line array and tiered seating.",
    website: "www.roguetheatre.org"
  },
  {
    id: "ragland-theater-klamath-falls",
    name: "Ross Ragland Theater",
    capacity: 780,
    address: "218 N 7th St, Klamath Falls, OR 97601",
    city: "Klamath Falls",
    genres: ["Country", "Folk", "Classical", "Rock", "Theatre"],
    contactEmail: "boxoffice@ragland.org",
    contactPhone: "(541) 884-5483",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 780 guests] Beautifully restored 1940 Art Deco theater in Klamath Falls serving the Klamath Basin with national touring concert production.",
    website: "www.ragland.org"
  },
  {
    id: "mia-and-pias-klamath-falls",
    name: "Mia & Pia's Pizzeria & Brewhouse Stage",
    capacity: 150,
    address: "3545 Summers Ln, Klamath Falls, OR 97603",
    city: "Klamath Falls",
    genres: ["Classic Rock", "Blues", "Americana", "Country"],
    contactEmail: "miapiabrewing@gmail.com",
    contactPhone: "(541) 884-4880",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Local Klamath Falls brewpub with spacious indoor family seating and outdoor covered beer garden stage for touring regional acts.",
    website: "www.facebook.com/miapiapizzeria"
  },

  // Oregon Coast (Astoria, Cannon Beach, Tillamook, Newport, Florence, Coos Bay)
  {
    id: "liberty-theatre-astoria",
    name: "Liberty Theatre",
    capacity: 650,
    address: "1203 Commercial St, Astoria, OR 97103",
    city: "Astoria",
    genres: ["Classical", "Rock", "Folk", "Jazz", "Americana"],
    contactEmail: "info@libertyastoria.org",
    contactPhone: "(503) 325-5922",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 650 guests] Crown jewel 1925 Italian Renaissance vaudeville theater in historic Astoria at the mouth of the Columbia River. Restored fresco walls and grand sound.",
    website: "www.libertyastoria.org"
  },
  {
    id: "labor-temple-astoria",
    name: "Labor Temple Diner & Bar",
    capacity: 120,
    address: "934 Duane St, Astoria, OR 97103",
    city: "Astoria",
    genres: ["Punk", "Garage Rock", "Country", "Americana"],
    contactEmail: "labortempleastoria@gmail.com",
    contactPhone: "(503) 325-7701",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Historic 1930s working-class union hall turned rock & roll dive. Stiff drinks, late-night diner classics, and high-octane weekend live shows.",
    website: "www.facebook.com/labortempleastoria"
  },
  {
    id: "fort-george-lovell-astoria",
    name: "Fort George Brewery - Lovell Showroom",
    capacity: 250,
    address: "426 14th St, Astoria, OR 97103",
    city: "Astoria",
    genres: ["Indie Rock", "Bluegrass", "Folk", "Americana", "Funk"],
    contactEmail: "music@fortgeorgebrewery.com",
    contactPhone: "(503) 325-7468",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Restored 1920s brick auto showroom inside the Fort George brewing compound. Hosts free Sunday music series and touring Pacific Northwest bands.",
    website: "www.fortgeorgebrewery.com"
  },
  {
    id: "prunty-barn-tillamook",
    name: "Pelican Brewing Siletz Bay Stage",
    capacity: 220,
    address: "5911 SW Hwy 101, Lincoln City, OR 97367",
    city: "Lincoln City",
    genres: ["Americana", "Acoustic", "Blues", "Folk"],
    contactEmail: "events@pelicanbrewing.com",
    contactPhone: "(541) 614-4260",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Coastal brewery venue on Siletz Bay with sweeping ocean views, cedar woodwork, and live touring musicians.",
    website: "www.pelicanbrewing.com"
  },
  {
    id: "newport-performing-arts-center",
    name: "Newport Performing Arts Center - Alice Silverman Theatre",
    capacity: 398,
    address: "777 W Olive St, Newport, OR 97365",
    city: "Newport",
    genres: ["Classical", "Jazz", "World", "Folk", "Acoustic"],
    contactEmail: "info@coastarts.org",
    contactPhone: "(541) 265-2787",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 398 guests] Premier coastal cultural center located in the historic Nye Beach district of Newport. Superb acoustic design and full technical staffing.",
    website: "www.coastarts.org"
  },
  {
    id: "bier-one-brewing-newport",
    name: "Bier One Taproom Stage",
    capacity: 110,
    address: "255 Commercial St, Newport, OR 97365",
    city: "Newport",
    genres: ["Rock", "Blues", "Indie", "Americana"],
    contactEmail: "bieronebrewing@gmail.com",
    contactPhone: "(541) 265-2337",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 110 guests] Downtown Newport bayfront craft beer pub with rotating regional taps and intimate live music performances.",
    website: "www.facebook.com/bierone"
  },
  {
    id: "egyptian-theatre-coos-bay",
    name: "Historic Egyptian Theatre",
    capacity: 770,
    address: "229 S Broadway, Coos Bay, OR 97420",
    city: "Coos Bay",
    genres: ["Classic Rock", "Folk", "Country", "Tribute"],
    contactEmail: "info@egyptiantheatreoss.com",
    contactPhone: "(541) 269-8650",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 770 guests] Rare 1925 Egyptian Revival movie palace on Oregon's southern coast, complete with working Mighty Wurlitzer organ and concert stage.",
    website: "www.egyptiantheatreoss.com"
  },
  {
    id: "7-devils-brewing-coos-bay",
    name: "7 Devils Brewery & Taproom Stage",
    capacity: 150,
    address: "247 S 2nd St, Coos Bay, OR 97420",
    city: "Coos Bay",
    genres: ["Indie Folk", "Americana", "Bluegrass", "Funk"],
    contactEmail: "music@7devilsbrewery.com",
    contactPhone: "(541) 808-3738",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Community craft brewery in Coos Bay hosting live music weekly with locally sourced coastal seafood and artisan ales.",
    website: "www.7devilsbrewery.com"
  },

  // Columbia River Gorge & Mt. Hood (Hood River, The Dalles, Cascade Locks, Government Camp)
  {
    id: "pfeim-brewing-hood-river",
    name: "pFriem Family Brewers Tasting Room",
    capacity: 160,
    address: "707 Portway Ave #101, Hood River, OR 97031",
    city: "Hood River",
    genres: ["Acoustic", "Indie Folk", "Americana", "Jazz"],
    contactEmail: "info@pfriembeer.com",
    contactPhone: "(541) 321-0490",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 160 guests] World-renowned Belgian-inspired craft brewery on the Hood River waterfront with views of the Columbia Gorge and live seasonal acoustic sessions.",
    website: "www.pfriembeer.com"
  },
  {
    id: "the-ruins-hood-river",
    name: "The Ruins",
    capacity: 450,
    address: "13 Railroad St, Hood River, OR 97031",
    city: "Hood River",
    genres: ["Indie Rock", "Funk", "Americana", "Reggae", "Bluegrass"],
    contactEmail: "booking@theruinshoodriver.com",
    contactPhone: "(541) 308-0700",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 450 guests] Stunning outdoor/indoor venue set within the stone ruins of a 100-year-old fruit packing cannery in downtown Hood River. Full concert audio.",
    website: "www.theruinshoodriver.com"
  },
  {
    id: "double-mountain-brewery-hood-river",
    name: "Double Mountain Brewery & Cidery",
    capacity: 180,
    address: "8 4th St, Hood River, OR 97031",
    city: "Hood River",
    genres: ["Blues", "Funk", "Rock", "Bluegrass"],
    contactEmail: "music@doublemountainbrewery.com",
    contactPhone: "(541) 387-0042",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Downtown Hood River institution famous for hop-forward ales, New Haven pizza, and weekend live touring roots/funk bands on the taproom stage.",
    website: "www.doublemountainbrewery.com"
  },
  {
    id: "river-tap-the-dalles",
    name: "Rivertap Pub & Stage",
    capacity: 140,
    address: "703 E 2nd St, The Dalles, OR 97058",
    city: "The Dalles",
    genres: ["Americana", "Blues", "Rock", "Country"],
    contactEmail: "rivertappub@gmail.com",
    contactPhone: "(541) 296-7870",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Historic brick pub in downtown The Dalles featuring craft beers, regional Northwest wines, and live touring musicians every weekend.",
    website: "www.rivertap.com"
  },
  {
    id: "granada-theatre-the-dalles",
    name: "Granada Theatre",
    capacity: 350,
    address: "221 E 2nd St, The Dalles, OR 97058",
    city: "The Dalles",
    genres: ["Classic Rock", "Country", "Tribute", "Blues"],
    contactEmail: "granadadalles@gmail.com",
    contactPhone: "(541) 370-2550",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] 1929 Spanish Moorish historic movie house and dinner theater in The Dalles with table seating and raised concert stage.",
    website: "www.granadatheatredalles.com"
  },
  {
    id: "charlys-saloon-government-camp",
    name: "Charlie's Mountain View",
    capacity: 120,
    address: "88462 Government Camp Loop, Government Camp, OR 97028",
    city: "Government Camp",
    genres: ["Rock", "Country", "Americana", "Bluegrass"],
    contactEmail: "charliesmthood@gmail.com",
    contactPhone: "(503) 272-3333",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Legendary Mt. Hood ski mountaineering tavern in Government Camp. Hearty burgers, roaring fireplace, and rocking weekend apres-ski bands.",
    website: "www.facebook.com/charliesmountainview"
  },

  // Eastern Oregon (Pendleton, La Grande, Baker City, Enterprise, Ontario, Burns)
  {
    id: "vert-auditorium-pendleton",
    name: "Vert Auditorium",
    capacity: 800,
    address: "480 SW Dorion Ave, Pendleton, OR 97801",
    city: "Pendleton",
    genres: ["Country", "Americana", "Rock", "Classical"],
    contactEmail: "parks@pendleton.or.us",
    contactPhone: "(541) 276-8100",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 800 guests] Historic 1936 Art Deco municipal theater in downtown Pendleton, famous for the Round-Up and hosting national country/roots touring acts.",
    website: "www.pendletonparksandrec.com"
  },
  {
    id: "great-keck-hall-pendleton",
    name: "Great Pacific Wine & Coffee Co. Stage",
    capacity: 120,
    address: "403 S Main St, Pendleton, OR 97801",
    city: "Pendleton",
    genres: ["Indie Folk", "Americana", "Singer-Songwriter", "Jazz"],
    contactEmail: "greatpacificwine@gmail.com",
    contactPhone: "(541) 276-1350",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Historic 1887 Masonic brick lodge on Main Street serving woodfired pizzas, espresso, and hosting touring folk/indie acoustic musicians.",
    website: "www.greatpacific.biz"
  },
  {
    id: "church-hall-la-grande",
    name: "HQ La Grande (High Quality Concert Hall)",
    capacity: 200,
    address: "112 Depot St, La Grande, OR 97850",
    city: "La Grande",
    genres: ["Indie Rock", "Americana", "Jazz", "Electronic", "Punk"],
    contactEmail: "hqlaGrande@gmail.com",
    contactPhone: "(541) 605-0442",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] Revitalized historic depot warehouse venue in eastern Oregon supporting regional and national touring independent artists with pro sound.",
    website: "www.hqlaGrande.com"
  },
  {
    id: "liberty-theatre-la-grande",
    name: "Liberty Theatre La Grande",
    capacity: 450,
    address: "1010 Adams Ave, La Grande, OR 97850",
    city: "La Grande",
    genres: ["Classical", "Rock", "Folk", "Theatre"],
    contactEmail: "info@liberty-lagrande.org",
    contactPhone: "(541) 624-5264",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 450 guests] Historic 1910 vaudeville theater in downtown La Grande undergoing major cultural restoration with active concert staging.",
    website: "www.liberty-lagrande.org"
  },
  {
    id: "church-ok-theatre-enterprise",
    name: "OK Theatre",
    capacity: 350,
    address: "208 W Main St, Enterprise, OR 97828",
    city: "Enterprise",
    genres: ["Americana", "Indie Folk", "Country", "Rock", "Bluegrass"],
    contactEmail: "booking@theoktheatre.com",
    contactPhone: "(541) 426-3023",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] Opened in 1919 in the Wallowa Mountain valley, one of the oldest operating theaters in Oregon. Renowned for hosting national indie folk and roots tours.",
    website: "www.theoktheatre.com"
  },
  {
    id: "geiser-grand-baker-city",
    name: "Geiser Grand Hotel - Palm Court Ballroom",
    capacity: 200,
    address: "1996 Main St, Baker City, OR 97814",
    city: "Baker City",
    genres: ["Jazz", "Classical", "Acoustic", "Americana"],
    contactEmail: "events@geisergrand.com",
    contactPhone: "(541) 523-1889",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] Victorian 1889 luxury hotel with breathtaking stained-glass ceiling, mahogany fixtures, and regular live jazz/acoustic concert dinners.",
    website: "www.geisergrand.com"
  },
  {
    id: "barley-browns-baker-city",
    name: "Barley Brown's Beer Taphouse Stage",
    capacity: 150,
    address: "2190 Main St, Baker City, OR 97814",
    city: "Baker City",
    genres: ["Bluegrass", "Rock", "Americana", "Blues"],
    contactEmail: "info@barleybrownsbeer.com",
    contactPhone: "(541) 523-4266",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Multi-award-winning GABF craft brewery on historic Main Street hosting lively weekend touring bands.",
    website: "www.barleybrownsbeer.com"
  },
  {
    id: "four-rivers-cultural-center-ontario",
    name: "Four Rivers Cultural Center - Meyer McLean Performing Arts Theater",
    capacity: 650,
    address: "676 SW 5th Ave, Ontario, OR 97914",
    city: "Ontario",
    genres: ["Country", "Tejano", "World", "Classical", "Rock"],
    contactEmail: "events@4rcc.com",
    contactPhone: "(541) 889-8191",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 650 guests] State-of-the-art regional theater on the Oregon-Idaho border featuring continental seating, fly tower, and professional tour production gear.",
    website: "www.4rcc.com"
  }
];

// Let's write `src/data/orVenues.ts`
const orContent = `import { Venue } from "../types";

export const OREGON_VENUES: Venue[] = ${JSON.stringify(oregonVenues, null, 2)};
`;

fs.writeFileSync(path.join(process.cwd(), 'src/data/orVenues.ts'), orContent, 'utf-8');
console.log(`Wrote ${oregonVenues.length} Oregon venues to src/data/orVenues.ts`);
