import fs from 'fs';
import path from 'path';

// Let's create an exhaustive collection of 105 Oregon venues and 105 Washington venues (total 210+ PNW venues)

const waVenues = [
  // Seattle & King County
  {
    id: "madame-lous-seattle",
    name: "Madame Lou's",
    capacity: 300,
    address: "2505 1st Ave, Seattle, WA 98121",
    city: "Seattle",
    genres: ["Indie Rock", "Post-Punk", "Electronic", "Dream Pop"],
    contactEmail: "booking@thecrocodile.com",
    contactPhone: "(206) 441-4618",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 300 guests] Intimate basement showroom inside the iconic Crocodile complex in Belltown. Features pristine d&b line arrays, low ceilings with moody red neon, and a dedicated artist hospitality green room with private load-in elevator.",
    website: "www.thecrocodile.com/madame-lous"
  },
  {
    id: "the-vera-project-seattle",
    name: "The Vera Project",
    capacity: 350,
    address: "305 Harrison St, Seattle, WA 98109",
    city: "Seattle",
    genres: ["Punk", "Hardcore", "Indie Rock", "Emo", "All-Ages"],
    contactEmail: "booking@theveraproject.org",
    contactPhone: "(206) 956-8372",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] Seattle Center's legendary all-ages volunteer-fueled music hall and screenprint studio. Known for an energetic room, heavy sub-bass response, strict safe-space policies, and wide street load-in ramp.",
    website: "www.theveraproject.org"
  },
  {
    id: "showbox-sodo-seattle",
    name: "Showbox SoDo",
    capacity: 1150,
    address: "1700 1st Ave S, Seattle, WA 98134",
    city: "Seattle",
    genres: ["Alternative Rock", "Hip-Hop", "Metal", "Electronic", "Pop"],
    contactEmail: "booking@showboxpresents.com",
    contactPhone: "(206) 652-0444",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1150 guests] Massive industrial brick concert hall in Seattle's stadium district. Features soaring timber beams, wide open sightlines, world-class L-Acoustics tour PA, and dedicated tour bus parking bays.",
    website: "www.showboxpresents.com"
  },
  {
    id: "moore-theatre-seattle",
    name: "The Moore Theatre",
    capacity: 1800,
    address: "1932 2nd Ave, Seattle, WA 98101",
    city: "Seattle",
    genres: ["Rock", "Indie", "Folk", "Comedy", "Acoustic"],
    contactEmail: "booking@stgpresents.org",
    contactPhone: "(206) 682-1414",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1800 guests] The oldest operating theater in Seattle (opened 1907). Boasts historic gilded proscenium, dual balconies, legendary acoustic resonance, and iconic grunge tour history.",
    website: "www.stgpresents.org/moore"
  },
  {
    id: "neptune-theatre-seattle",
    name: "Neptune Theatre",
    capacity: 800,
    address: "1303 NE 45th St, Seattle, WA 98105",
    city: "Seattle",
    genres: ["Indie Rock", "Synthpop", "Psychedelic", "Folk Rock"],
    contactEmail: "booking@stgpresents.org",
    contactPhone: "(206) 682-1414",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 800 guests] Historic 1921 theater in the University District converted into a state-of-the-art multi-tier general admission music hall. Features stained glass nautical windows and crystal-clear acoustic arrays.",
    website: "www.stgpresents.org/neptune"
  },
  {
    id: "sea-monster-lounge-seattle",
    name: "Sea Monster Lounge",
    capacity: 120,
    address: "2202 N 45th St, Seattle, WA 98103",
    city: "Seattle",
    genres: ["Funk", "Soul", "Jazz", "R&B", "Jam Band"],
    contactEmail: "seamonsterbooking@gmail.com",
    contactPhone: "(206) 633-1824",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Wallingford groove epicenter. Live funk, soul, and acid-jazz 7 nights a week. Tight stage setup, warm analog mixing board, and an intensely loyal crowd of dancers and musicians.",
    website: "www.seamonsterlounge.com"
  },
  {
    id: "fremont-abbey-arts-seattle",
    name: "Fremont Abbey Arts Center",
    capacity: 250,
    address: "4272 Fremont Ave N, Seattle, WA 98103",
    city: "Seattle",
    genres: ["Folk", "Indie Acoustic", "Chamber Pop", "Americana", "Ambient"],
    contactEmail: "booking@fremontabbey.org",
    contactPhone: "(206) 414-8325",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Restored 1914 brick church with curved wooden pews and warm natural acoustics. A quiet listening room strictly dedicated to all-ages acoustic and ambient performances.",
    website: "www.fremontabbey.org"
  },
  {
    id: "ballard-homestead-seattle",
    name: "Ballard Homestead",
    capacity: 160,
    address: "6541 Jones Ave NW, Seattle, WA 98117",
    city: "Seattle",
    genres: ["Acoustic", "Folk", "Americana", "Bluegrass", "Singer-Songwriter"],
    contactEmail: "curator@ballardhomestead.org",
    contactPhone: "(206) 414-8325",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 160 guests] A cozy community arts sanctuary with original fir floors and vaulted ceilings. Perfect for unplugged sets, storytelling, and acoustic band tours.",
    website: "www.ballardhomestead.org"
  },
  {
    id: "southgate-roller-rink-seattle",
    name: "Southgate Roller Rink Stage",
    capacity: 400,
    address: "9646 17th Ave SW, Seattle, WA 98106",
    city: "Seattle",
    genres: ["Punk", "Garage Rock", "Surf Rock", "Rockabilly"],
    contactEmail: "shows@southgaterollerrink.com",
    contactPhone: "(206) 707-6949",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 400 guests] Authentic vintage roller rink in White Center hosting live bands at center-rink while fans skate or pack the stage perimeter. Wild energy, full bar, and spacious load-in.",
    website: "www.southgaterollerrink.com"
  },
  {
    id: "jules-maes-saloon-seattle",
    name: "Jules Maes Saloon",
    capacity: 140,
    address: "5919 Airport Way S, Seattle, WA 98108",
    city: "Seattle",
    genres: ["Americana", "Outlaw Country", "Rock & Roll", "Honky Tonk"],
    contactEmail: "booking@julesmaes.com",
    contactPhone: "(206) 957-7766",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Seattle's oldest saloon (established 1888) in historic Georgetown. Features antique oak bar, backroom music stage, cold Rainier on tap, and a dedicated live sound console.",
    website: "www.julesmaes.com"
  },
  {
    id: "the-kraken-bar-seattle",
    name: "The Kraken Bar & Lounge",
    capacity: 110,
    address: "5224 University Way NE, Seattle, WA 98105",
    city: "Seattle",
    genres: ["Punk", "Metal", "Hardcore", "Sludge", "Thrash"],
    contactEmail: "booking@thekrakenbar.com",
    contactPhone: "(206) 525-4128",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 110 guests] Raw dive bar on the Ave in the U-District. Grungy stage, roaring monitor wedges, pinball machines, and a haven for heavy metal and underground punk tours.",
    website: "www.thekrakenbar.com"
  },
  {
    id: "victory-lounge-seattle",
    name: "Victory Lounge",
    capacity: 100,
    address: "433 Eastlake Ave E, Seattle, WA 98109",
    city: "Seattle",
    genres: ["Punk", "Garage Rock", "Indie", "Noise Rock"],
    contactEmail: "victoryloungeseattle@gmail.com",
    contactPhone: "(206) 382-4467",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 100 guests] Intimate Eastlake rock dive bar right near South Lake Union. Friendly staff, loud drums, great sightlines, and DIY touring band hospitality.",
    website: "www.facebook.com/victoryloungeseattle"
  },
  {
    id: "belltown-yacht-club-seattle",
    name: "Belltown Yacht Club",
    capacity: 150,
    address: "2322 1st Ave, Seattle, WA 98121",
    city: "Seattle",
    genres: ["Garage Rock", "Psychedelic", "Indie Rock", "Glam Punk"],
    contactEmail: "booking@belltownyachtclub.com",
    contactPhone: "(206) 448-6288",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Subterranean rock club beneath the Screwdriver Bar in Belltown. Features low ceilings, killer sound engineer, vintage maritime decor, and a gritty rock & roll vibe.",
    website: "www.belltownyachtclub.com"
  },
  {
    id: "washington-hall-seattle",
    name: "Washington Hall",
    capacity: 450,
    address: "153 14th Ave, Seattle, WA 98122",
    city: "Seattle",
    genres: ["Soul", "World", "Hip-Hop", "Jazz", "Folk"],
    contactEmail: "events@washingtonhall.org",
    contactPhone: "(206) 323-2339",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 450 guests] Historic 1908 Central District hall where Duke Ellington, Billie Holiday, and Jimi Hendrix once performed. Gorgeous wrap-around wooden balcony and warm acoustic envelope.",
    website: "www.washingtonhall.org"
  },
  {
    id: "town-hall-seattle",
    name: "Town Hall Seattle - The Forum",
    capacity: 850,
    address: "1119 8th Ave, Seattle, WA 98101",
    city: "Seattle",
    genres: ["Classical", "Jazz", "World", "Chamber Music", "Indie Acoustic"],
    contactEmail: "rentals@townhallseattle.org",
    contactPhone: "(206) 652-4255",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 850 guests] Downtown Seattle landmark cultural center fully renovated with custom Meyer Sound acoustic tuning, tiered theater seating, and pristine broadcast recording capabilities.",
    website: "www.townhallseattle.org"
  },
  {
    id: "rabbit-box-theatre-seattle",
    name: "The Rabbit Box Theatre",
    capacity: 130,
    address: "94 Pike St, Seattle, WA 98101",
    city: "Seattle",
    genres: ["Cabaret", "Folk", "Indie Rock", "Jazz", "Americana"],
    contactEmail: "booking@therabbitboxseattle.com",
    contactPhone: "(206) 402-4577",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Speakeasy-style music room nestled downstairs in Pike Place Market. Features velvet banquettes, artisan cocktails, baby grand piano, and an intimate listening stage.",
    website: "www.therabbitboxseattle.com"
  },
  {
    id: "rendezvous-jewelbox-seattle",
    name: "The Rendezvous & JewelBox Theater",
    capacity: 90,
    address: "2322 2nd Ave, Seattle, WA 98121",
    city: "Seattle",
    genres: ["Cabaret", "Indie Pop", "Experimental", "Folk", "Lounge"],
    contactEmail: "booking@therendezvous.rocks",
    contactPhone: "(206) 441-5823",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 90 guests] Legendary 1926 Belltown gem featuring an authentic velvet-curtained jewel-box proscenium stage. High intimacy, vintage film screening projector, and full dining room.",
    website: "www.therendezvousseattle.com"
  },
  {
    id: "vermillion-art-bar-seattle",
    name: "Vermillion Art Gallery & Bar",
    capacity: 100,
    address: "1508 11th Ave, Seattle, WA 98122",
    city: "Seattle",
    genres: ["Electronic", "Experimental", "Synthwave", "Noise", "Indie"],
    contactEmail: "vermillionseattle@gmail.com",
    contactPhone: "(206) 709-9797",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 100 guests] Capitol Hill neighborhood art lounge and experimental music incubator. Rotating gallery walls, craft ciders, warm crowd, and modular DJ/live synth setups.",
    website: "www.vermillionseattle.com"
  },
  {
    id: "high-dive-seattle",
    name: "High Dive",
    capacity: 220,
    address: "513 N 36th St, Seattle, WA 98103",
    city: "Seattle",
    genres: ["Indie Rock", "Funk", "Jam Band", "Reggae", "Synthpop"],
    contactEmail: "booking@highdiveseattle.com",
    contactPhone: "(206) 632-0212",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Vibrant live music club in the heart of Fremont. Excellent sound board, raised stage, multi-tier viewing, and energetic dance floor.",
    website: "www.highdiveseattle.com"
  },
  {
    id: "clock-out-lounge-seattle",
    name: "Clock-Out Lounge",
    capacity: 275,
    address: "4864 Beacon Ave S, Seattle, WA 98108",
    city: "Seattle",
    genres: ["Indie Rock", "Punk", "Comedy", "Post-Punk", "Soul"],
    contactEmail: "booking@clockoutlounge.com",
    contactPhone: "(206) 257-4988",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 275 guests] Beacon Hill's favorite music hub and pizza paradise. Top tier live audio, spacious dance floor, and Breezy Town pizza kitchen.",
    website: "www.clockoutlounge.com"
  },
  {
    id: "timbre-room-seattle",
    name: "Timbre Room",
    capacity: 140,
    address: "1809 Minor Ave, Seattle, WA 98101",
    city: "Seattle",
    genres: ["Electronic", "House", "Techno", "Experimental", "Hyperpop"],
    contactEmail: "booking@kremwerk.com",
    contactPhone: "(206) 682-2960",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Intimate timber-clad showroom inside the Kremwerk complex. Features custom wooden acoustic diffusion, punchy subwoofers, and queer nightlife forward programming.",
    website: "www.kremwerk.com/timbre-room"
  },
  {
    id: "substation-seattle",
    name: "Substation Seattle",
    capacity: 250,
    address: "645 NW 45th St, Seattle, WA 98107",
    city: "Seattle",
    genres: ["Metal", "Punk", "Electronic", "Industrial", "Experimental"],
    contactEmail: "booking@substationseattle.com",
    contactPhone: "(206) 782-9900",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Multi-room underground music and recording compound in Ballard. High power bass bins, dual stages, and late-night touring shows.",
    website: "www.substationseattle.com"
  },
  {
    id: "royal-room-seattle",
    name: "The Royal Room",
    capacity: 200,
    address: "5000 Rainier Ave S, Seattle, WA 98118",
    city: "Seattle",
    genres: ["Jazz", "Soul", "Global", "Big Band", "Avant-Garde"],
    contactEmail: "booking@theroyalroomseattle.com",
    contactPhone: "(206) 906-9920",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] Renowned musicians' listening lounge and supper club in Columbia City with grand piano, multi-track recording studio, and nightly live music.",
    website: "www.theroyalroomseattle.com"
  },
  {
    id: "conor-byrne-pub-seattle",
    name: "Conor Byrne Pub",
    capacity: 150,
    address: "5140 Ballard Ave NW, Seattle, WA 98107",
    city: "Seattle",
    genres: ["Folk", "Americana", "Irish Traditional", "Bluegrass", "Indie"],
    contactEmail: "booking@conorbyrnepub.com",
    contactPhone: "(206) 784-3640",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Historic Ballard brick tavern famous as an incubator for Seattle's roots, folk, and singer-songwriter explosion. Warm brick and wooden bar.",
    website: "www.conorbyrnepub.com"
  },
  {
    id: "skylark-cafe-seattle",
    name: "The Skylark Cafe & Club",
    capacity: 180,
    address: "3803 Delridge Way SW, Seattle, WA 98106",
    city: "Seattle",
    genres: ["Indie Rock", "Pop-Punk", "Americana", "Cover Bands"],
    contactEmail: "booking@skylarkcafe.com",
    contactPhone: "(206) 935-2111",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] West Seattle live music venue and diner with full stage, pro sound technician, spacious patio, and hearty comfort food.",
    website: "www.skylarkcafe.com"
  },
  {
    id: "darrells-tavern-shoreline",
    name: "Darrell's Tavern",
    capacity: 120,
    address: "18041 Aurora Ave N, Shoreline, WA 98133",
    city: "Shoreline",
    genres: ["Garage Rock", "Rockabilly", "Surf", "Punk", "Blues"],
    contactEmail: "darrellstavern@gmail.com",
    contactPhone: "(206) 542-2789",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Legendary retro lounge on Highway 99 with vintage mid-century signs, great stage, and enthusiastic garage/surf rock community.",
    website: "www.darrellstavern.com"
  },
  {
    id: "the-run-away-seattle",
    name: "The Runaway at Neumos",
    capacity: 100,
    address: "925 E Pike St, Seattle, WA 98122",
    city: "Seattle",
    genres: ["Indie Pop", "Electronic", "DJ", "Acoustic"],
    contactEmail: "booking@neumos.com",
    contactPhone: "(206) 709-9442",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 100 guests] Intimate front bar inside the Neumos complex on Capitol Hill. Great cocktails, neon atmosphere, and intimate live pop/indie showcases.",
    website: "www.neumos.com"
  },
  {
    id: "blue-moon-tavern-seattle",
    name: "Blue Moon Tavern",
    capacity: 110,
    address: "712 NE 45th St, Seattle, WA 98105",
    city: "Seattle",
    genres: ["Punk", "Poetry", "Garage Rock", "Folk", "Indie"],
    contactEmail: "booking@bluemoonseattle.com",
    contactPhone: "(206) 675-9110",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 110 guests] Historic 1934 bohemian watering hole frequented by Allen Ginsberg, Dylan Thomas, and Theodore Roethke. Continues hosting live underground rock and poetry.",
    website: "www.bluemoonseattle.com"
  },
  {
    id: "woodland-theater-seattle",
    name: "Woodland Theater",
    capacity: 80,
    address: "608 NW 65th St, Seattle, WA 98117",
    city: "Seattle",
    genres: ["Experimental", "Drone", "Avant-Garde", "Noise", "Free Jazz"],
    contactEmail: "woodlandtheaterseattle@gmail.com",
    contactPhone: "(206) 782-9901",
    hasPA: true,
    hasLighting: false,
    description: "[Capacity: 80 guests] Cozy Ballard DIY cooperative performance space dedicated to boundary-pushing audio explorations, cassette releases, and experimental touring musicians.",
    website: "www.woodlandtheater.org"
  },
  {
    id: "central-saloon-seattle",
    name: "The Central Saloon",
    capacity: 200,
    address: "207 1st Ave S, Seattle, WA 98104",
    city: "Seattle",
    genres: ["Grunge", "Rock & Roll", "Blues", "Punk"],
    contactEmail: "booking@centralsaloon.com",
    contactPhone: "(206) 622-0209",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] Established in 1892, Seattle's oldest saloon and birthplace of Grunge (Nirvana, Soundgarden, Alice in Chains, Mother Love Bone early shows).",
    website: "www.centralsaloon.com"
  },

  // Tacoma & Pierce County
  {
    id: "jazzbones-tacoma",
    name: "Jazzbones",
    capacity: 280,
    address: "2803 6th Ave, Tacoma, WA 98406",
    city: "Tacoma",
    genres: ["Rock", "Blues", "Funk", "Reggae", "Tribute"],
    contactEmail: "booking@jazzbones.com",
    contactPhone: "(253) 396-9169",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 280 guests] Iconic 6th Avenue nightclub in Tacoma. Known for top-tier digital sound desk, raised performance stage, dance floor, and bustling weekend crowds.",
    website: "www.jazzbones.com"
  },
  {
    id: "real-art-tacoma",
    name: "Real Art Tacoma",
    capacity: 200,
    address: "5412 S Tacoma Way, Tacoma, WA 98409",
    city: "Tacoma",
    genres: ["Punk", "Hardcore", "Metal", "Emo", "Indie Rock", "All-Ages"],
    contactEmail: "realarttacoma@gmail.com",
    contactPhone: "(253) 474-1212",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] South Tacoma's premier all-ages non-profit music space. Dedicated to safe, accessible DIY live concerts, youth audio engineering education, and touring independent bands.",
    website: "www.realarttacoma.com"
  },
  {
    id: "bobs-java-jive-tacoma",
    name: "Bob's Java Jive",
    capacity: 90,
    address: "2102 S Tacoma Way, Tacoma, WA 98409",
    city: "Tacoma",
    genres: ["Garage Rock", "Rockabilly", "Psych", "Punk", "Country"],
    contactEmail: "bobsjavajive@gmail.com",
    contactPhone: "(253) 475-9843",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 90 guests] Legendary 1927 coffee-pot shaped roadside architectural icon. Inside is a neon, tiki-and-velvet soaked rock sanctuary with historic stage pedigree and jukebox dive charm.",
    website: "www.facebook.com/bobsjavajive"
  },
  {
    id: "plaid-pig-tacoma",
    name: "The Plaid Pig Live Music Lounge",
    capacity: 120,
    address: "5214 S Tacoma Way, Tacoma, WA 98409",
    city: "Tacoma",
    genres: ["Punk", "Hardcore", "Thrash", "Ska", "Heavy Rock"],
    contactEmail: "theplaidpig@gmail.com",
    contactPhone: "(253) 301-3838",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Vibrant punk and underground rock refuge on South Tacoma Way. Features full backline, pinball room, great vegan street food, and heavy bass reinforcement.",
    website: "www.facebook.com/plaidpigtacoma"
  },
  {
    id: "kvlt-mead-tacoma",
    name: "KVLT Mead Hall",
    capacity: 80,
    address: "4518 S Tacoma Way, Tacoma, WA 98409",
    city: "Tacoma",
    genres: ["Black Metal", "Doom", "Dark Ambient", "Dungeon Synth", "Folk"],
    contactEmail: "booking@kvltmead.com",
    contactPhone: "(253) 302-3904",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 80 guests] Artisan meadery and heavy music venue catering to extreme metal, doom, and atmospheric acoustic artists. Dim candlelit atmosphere and crystal-clear acoustic acoustics.",
    website: "www.kvltmead.com"
  },
  {
    id: "pantages-theater-tacoma",
    name: "Pantages Theater",
    capacity: 1180,
    address: "901 Broadway, Tacoma, WA 98402",
    city: "Tacoma",
    genres: ["Classical", "Rock", "Jazz", "Broadway", "Pop"],
    contactEmail: "booking@tacomavenues.org",
    contactPhone: "(253) 591-5894",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1180 guests] Beautifully restored 1918 Greco-Roman vaudeville theater in downtown Tacoma with plush seating, grand acoustic shell, and full production touring infrastructure.",
    website: "www.tacomavenues.org"
  },
  {
    id: "the-spar-tacoma",
    name: "The Spar Tavern",
    capacity: 125,
    address: "2121 N 30th St, Tacoma, WA 98403",
    city: "Tacoma",
    genres: ["Blues", "R&B", "Roots Rock", "Americana"],
    contactEmail: "music@thespartavern.com",
    contactPhone: "(253) 627-8215",
    hasPA: true,
    hasLighting: false,
    description: "[Capacity: 125 guests] Old Town Tacoma historic waterfront tavern (since 1917) hosting premier Pacific Northwest blues, roots, and soul bands every Sunday night.",
    website: "www.thespartavern.com"
  },
  {
    id: "chalet-theatre-enumclaw",
    name: "Chalet Theatre",
    capacity: 380,
    address: "1721 Cole St, Enumclaw, WA 98022",
    city: "Enumclaw",
    genres: ["Classic Rock", "Country", "Americana", "Tribute", "Indie"],
    contactEmail: "events@chalettheatre.com",
    contactPhone: "(360) 825-3000",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 380 guests] Historic 1928 Art Deco movie house and concert hall in the Mount Rainier foothills. Fully equipped with modern digital line arrays and backstage dressing rooms.",
    website: "www.chalettheatre.com"
  },
  {
    id: "tacoma-spanish-ballroom",
    name: "Spanish Ballroom at McMenamins Elks Temple",
    capacity: 700,
    address: "565 Broadway, Tacoma, WA 98402",
    city: "Tacoma",
    genres: ["Rock", "Indie", "Funk", "Americana", "Electronic"],
    contactEmail: "booking@mcmenamins.com",
    contactPhone: "(253) 300-8777",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 700 guests] Magnificent restored 1916 ballroom in Tacoma's historic Elks Temple. Soaring ceilings, intricate murals, grand sound rig, and on-site hotel/breweries.",
    website: "www.mcmenamins.com/elks-temple/spanish-ballroom"
  },
  {
    id: "airport-tavern-tacoma",
    name: "Airport Tavern Live Music Hall",
    capacity: 180,
    address: "5406 S Tacoma Way, Tacoma, WA 98409",
    city: "Tacoma",
    genres: ["Punk", "Metal", "Hard Rock", "Country"],
    contactEmail: "airporttaverntacoma@gmail.com",
    contactPhone: "(253) 475-4700",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Rowdy South Tacoma Way rock joint with full stage sound, pool tables, and packed weekend rock shows.",
    website: "www.airporttaverntacoma.com"
  },

  // Olympia & Thurston County
  {
    id: "levoyeur-olympia",
    name: "LeVoyeur",
    capacity: 150,
    address: "404 4th Ave E, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Indie Rock", "Punk", "Riot Grrrl", "Post-Hardcore", "Experimental"],
    contactEmail: "levoyeuroly@gmail.com",
    contactPhone: "(360) 943-5710",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Core historic pillar of the Pacific Northwest underground indie and Riot Grrrl explosion. All-vegan kitchen, dynamic sound system, and legendary tour stop.",
    website: "www.levoyeuroly.com"
  },
  {
    id: "capitol-theater-olympia",
    name: "Capitol Theater (Olympia Film Society)",
    capacity: 750,
    address: "206 5th Ave SE, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Indie Rock", "Folk", "Experimental", "Punk", "World"],
    contactEmail: "booking@olympiafilmsociety.org",
    contactPhone: "(360) 754-6670",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 750 guests] Historic 1924 theater in downtown Olympia with grand balcony, proscenium stage, and incredible room acoustics. Managed by the volunteer non-profit OFS.",
    website: "www.olympiafilmsociety.org"
  },
  {
    id: "cryptatropa-bar-olympia",
    name: "Cryptatropa Bar",
    capacity: 110,
    address: "421 4th Ave E, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Goth", "Darkwave", "Industrial", "Post-Punk", "Synth"],
    contactEmail: "cryptatropabooking@gmail.com",
    contactPhone: "(360) 705-0909",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 110 guests] Gothic apothecary bar with antique chandeliers, handcrafted botanical absinthes, and a loud, bass-heavy stage welcoming dark alternative acts.",
    website: "www.facebook.com/cryptatropa"
  },
  {
    id: "the-brotherhood-lounge-olympia",
    name: "The Brotherhood Lounge",
    capacity: 130,
    address: "119 Capitol Way N, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Indie Rock", "Folk Rock", "Garage", "Psych"],
    contactEmail: "brohoevents@gmail.com",
    contactPhone: "(360) 352-4153",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Olympia's oldest continuously operating tavern (since 1884). Features vintage shuffleboard, back lounge stage, and regular touring showcases.",
    website: "www.thebrotherhoodlounge.com"
  },
  {
    id: "mccoys-tavern-olympia",
    name: "McCoy's Tavern",
    capacity: 100,
    address: "418 4th Ave E, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Punk", "Hardcore", "Sludge Metal", "Rock"],
    contactEmail: "mccoystavernoly@gmail.com",
    contactPhone: "(360) 357-9905",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 100 guests] Gritty downtown dive with classic pool tables, loud monitor mix, and a legacy of raw punk performances.",
    website: "www.facebook.com/mccoystavern"
  },
  {
    id: "nicoles-bar-olympia",
    name: "Nicole's Bar",
    capacity: 160,
    address: "109 Legion Way SW, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Country", "Classic Rock", "Blues", "Pop"],
    contactEmail: "nicolesbaroly@gmail.com",
    contactPhone: "(360) 688-1322",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 160 guests] Downtown Olympia bar featuring regular weekend live bands, expansive dance floor, high-end cocktail service, and friendly regional crowds.",
    website: "www.nicolesbar.com"
  },
  {
    id: "rhythm-and-rye-olympia",
    name: "Rhythm & Rye Live Hall",
    capacity: 175,
    address: "311 Capitol Way N, Olympia, WA 98501",
    city: "Olympia",
    genres: ["Funk", "Jazz", "Bluegrass", "Jam Band", "Soul"],
    contactEmail: "rhythmandrye@gmail.com",
    contactPhone: "(360) 705-0760",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 175 guests] Premier downtown Olympia live music room specializing in high-energy roots, jazz, and jam grooves with custom analog sound desk.",
    website: "www.rhythmandrye.com"
  },

  // Bellingham & Whatcom County
  {
    id: "the-blue-room-bellingham",
    name: "The Blue Room",
    capacity: 200,
    address: "202 E Holly St #301, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Indie Rock", "Hip-Hop", "Jazz", "Funk", "All-Ages"],
    contactEmail: "booking@blueroombham.com",
    contactPhone: "(360) 656-6548",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] Third-floor loft concert room and all-ages performance space in downtown Bellingham. Superb sound engineers, exposed brick, and vibrant university audience.",
    website: "www.blueroombham.com"
  },
  {
    id: "boundary-bay-brewery-bellingham",
    name: "Boundary Bay Brewery - Mountain Room & Beer Garden",
    capacity: 350,
    address: "1107 Railroad Ave, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Bluegrass", "Funk", "Americana", "Roots Rock", "Reggae"],
    contactEmail: "music@bbaybrewery.com",
    contactPhone: "(360) 647-5593",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] Northwest craft brewing pioneer featuring an outdoor summer concert amphitheater and warm indoor cedar taproom stage for touring acts.",
    website: "www.bbaybrewery.com"
  },
  {
    id: "aslan-depot-bellingham",
    name: "Aslan Depot: Bar & Barrel House",
    capacity: 120,
    address: "1322 N State St, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Jazz", "Acoustic", "Indie Folk", "Soul", "Ambient"],
    contactEmail: "events@aslanbrewing.com",
    contactPhone: "(360) 393-4106",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Historic brick barrelhouse featuring barrel-aged beers, plush leather vintage chesterfield couches, and an intimate acoustic jazz & indie stage.",
    website: "www.aslanbrewing.com/depot"
  },
  {
    id: "makeshift-art-space-bellingham",
    name: "Make.Shift Art Space",
    capacity: 150,
    address: "306 Flora St, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Punk", "Indie", "Experimental", "Lo-Fi", "All-Ages"],
    contactEmail: "booking@makeshiftproject.com",
    contactPhone: "(360) 389-3569",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] All-ages non-profit DIY art and music hub. Outfitted with safe space ethics, band practice spaces, and a welcoming community room.",
    website: "www.makeshiftartspace.org"
  },
  {
    id: "mount-baker-theatre-bellingham",
    name: "Mount Baker Theatre - Walton Theatre Stage",
    capacity: 1500,
    address: "104 N Commercial St, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Rock", "Classical", "Folk", "Jazz", "World"],
    contactEmail: "programming@mountbakertheatre.com",
    contactPhone: "(360) 734-6080",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1500 guests] Pacific Northwest architectural landmark built in 1927. Offers grand mainstage touring production alongside the intimate 180-cap Walton Theatre blackbox room.",
    website: "www.mountbakertheatre.com"
  },
  {
    id: "structures-brewing-bellingham",
    name: "Structures Brewing Old Town Stage",
    capacity: 180,
    address: "601 W Holly St, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Heavy Metal", "Hardcore", "Doom", "Darkwave", "Indie"],
    contactEmail: "booking@structuresbrewing.com",
    contactPhone: "(360) 922-0310",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Old Town Bellingham brewery tasting room and music hall. Heavy metal vibe, top-tier draft menu, and loud, crisp live sound.",
    website: "www.structuresbrewing.com"
  },
  {
    id: "the-shakedown-bellingham",
    name: "The Shakedown",
    capacity: 220,
    address: "1212 N State St, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Punk", "Indie Rock", "Metal", "Garage Rock"],
    contactEmail: "booking@shakedownbellingham.com",
    contactPhone: "(360) 778-1067",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Bellingham's premiere rock club with top notch sound, pinball arcade next door (The Racket), and dedicated touring hospitality.",
    website: "www.shakedownbellingham.com"
  },
  {
    id: "wild-buffalo-bellingham",
    name: "Wild Buffalo House of Music",
    capacity: 450,
    address: "208 W Holly St, Bellingham, WA 98225",
    city: "Bellingham",
    genres: ["Funk", "Electronic", "Hip-Hop", "Rock", "Reggae"],
    contactEmail: "booking@wildbuffalo.net",
    contactPhone: "(360) 746-8733",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 450 guests] Downtown Bellingham's heavyweight live music venue. Boasts huge dance floor, concert lighting rig, heavy subs, and top regional/national touring acts.",
    website: "www.wildbuffalo.net"
  },

  // Everett & Snohomish County
  {
    id: "historic-everett-theatre",
    name: "Historic Everett Theatre",
    capacity: 800,
    address: "2911 Colby Ave, Everett, WA 98201",
    city: "Everett",
    genres: ["Classic Rock", "Tribute", "Blues", "Americana", "Comedy"],
    contactEmail: "booking@historiceveretttheatre.org",
    contactPhone: "(425) 258-6766",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 800 guests] Opened in 1901, one of the oldest operating theaters on the West Coast with majestic proscenium and historic acoustic resonance.",
    website: "www.historiceveretttheatre.org"
  },
  {
    id: "tonys-snohomish",
    name: "Tony V's Garage",
    capacity: 220,
    address: "1716 Hewitt Ave, Everett, WA 98201",
    city: "Everett",
    genres: ["Punk", "Metal", "Hard Rock", "Garage Rock"],
    contactEmail: "tonyvsgarage@gmail.com",
    contactPhone: "(425) 374-3567",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Legendary Everett live rock venue with full grill, craft beer taps, pinball, and a loud, energetic stage hosting local and touring rock acts.",
    website: "www.tonyvsgarage.com"
  },
  {
    id: "black-lab-gallery-everett",
    name: "Black Lab Gallery & Bar",
    capacity: 140,
    address: "1805 Hewitt Ave, Everett, WA 98201",
    city: "Everett",
    genres: ["Indie Rock", "Punk", "Experimental", "Folk", "All-Ages"],
    contactEmail: "blacklabgalleryeverett@gmail.com",
    contactPhone: "(425) 512-9476",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Contemporary art gallery, craft cocktail lounge, and live music venue in downtown Everett supporting independent touring artists.",
    website: "www.blacklabgallery.com"
  },
  {
    id: "scuttlebutt-taproom-everett",
    name: "Scuttlebutt Taproom & Stage",
    capacity: 180,
    address: "3314 Cedar St, Everett, WA 98201",
    city: "Everett",
    genres: ["Americana", "Blues", "Rock", "Acoustic"],
    contactEmail: "taproom@scuttlebuttbrewing.com",
    contactPhone: "(425) 257-9316",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Craft brewery production taproom with high timber ceilings, food trucks, and regular live music.",
    website: "www.scuttlebuttbrewing.com"
  },

  // Spokane & Eastern Washington
  {
    id: "knitting-factory-spokane",
    name: "Knitting Factory Spokane",
    capacity: 1500,
    address: "919 W Sprague Ave, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Rock", "Metal", "Hip-Hop", "Indie", "Electronic", "Country"],
    contactEmail: "spokanebooking@knittingfactory.com",
    contactPhone: "(509) 244-3277",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 1500 guests] Spokane's premier downtown concert hall. Features multi-level viewing, concert sound array, full tour production capabilities, and spacious green rooms.",
    website: "www.sp.knittingfactory.com"
  },
  {
    id: "the-big-dipper-spokane",
    name: "The Big Dipper Spokane",
    capacity: 220,
    address: "171 S Washington St, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Punk", "Hardcore", "Metal", "Indie Rock", "All-Ages"],
    contactEmail: "bigdipperevents@gmail.com",
    contactPhone: "(509) 863-8098",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Historic 1930s brick venue and long-standing indie/punk stronghold in Spokane. Dedicated to all-ages touring acts, great sound, and welcoming community.",
    website: "www.thebigdipperspokane.com"
  },
  {
    id: "berserk-bar-spokane",
    name: "Berserk Bar",
    capacity: 120,
    address: "125 S Stevens St, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Garage Rock", "Post-Punk", "Synthwave", "Noise", "Indie"],
    contactEmail: "berserkspokane@gmail.com",
    contactPhone: "(509) 315-5101",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Vibrant downtown Spokane arts bar with pinball lineup, rotating indie art exhibits, craft taps, and regular live punk/synth performances.",
    website: "www.facebook.com/berserkspokane"
  },
  {
    id: "the-chameleon-spokane",
    name: "The Chameleon Spokane",
    capacity: 350,
    address: "1801 W Sunset Blvd, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Indie Rock", "Electronic", "Funk", "Soul", "Hip-Hop"],
    contactEmail: "booking@chameleonspokane.com",
    contactPhone: "(509) 474-9040",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 350 guests] Revitalized music space in Spokane's West End. Outfitted with immersive stage lighting, acoustic treatment, and wide viewing sightlines.",
    website: "www.chameleonspokane.com"
  },
  {
    id: "baby-bar-spokane",
    name: "Baby Bar & Neato Burrito",
    capacity: 70,
    address: "827 W 1st Ave, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Indie", "Experimental", "Lo-Fi", "Acoustic", "Punk"],
    contactEmail: "neatoburritobabybar@gmail.com",
    contactPhone: "(509) 847-1234",
    hasPA: true,
    hasLighting: false,
    description: "[Capacity: 70 guests] Cozy, cult-favorite downtown Spokane hideaway serving fresh burritos in front and hosting DIY punk/indie/synth shows in the intimate back lounge.",
    website: "www.facebook.com/babybarspokane"
  },
  {
    id: "mootsys-spokane",
    name: "Mootsy's",
    capacity: 90,
    address: "406 W Sprague Ave, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Punk", "Garage Rock", "Rock & Roll", "Hardcore"],
    contactEmail: "mootsysbar@gmail.com",
    contactPhone: "(509) 838-1570",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 90 guests] Legendary downtown Spokane rock dive with stiff drinks, jukebox classics, and loud weekend live shows right on Sprague Ave.",
    website: "www.facebook.com/mootsys"
  },
  {
    id: "bing-crosby-theater-spokane",
    name: "Bing Crosby Theater",
    capacity: 756,
    address: "901 W Sprague Ave, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Acoustic", "Jazz", "Folk", "Americana", "Comedy"],
    contactEmail: "theatermanager@bingcrosbytheater.com",
    contactPhone: "(509) 227-7638",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 756 guests] Historic 1914 theater named after Spokane native Bing Crosby. Restored proscenium, plush seating, and acoustic clarity for national touring acts.",
    website: "www.bingcrosbytheater.com"
  },
  {
    id: "zola-spokane",
    name: "Zola",
    capacity: 140,
    address: "22 W Main Ave, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Funk", "Soul", "R&B", "Blues", "Pop"],
    contactEmail: "booking@zolaspokane.com",
    contactPhone: "(509) 624-2416",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Eclectic downtown restaurant and lounge constructed from recycled materials (including tilt-a-whirl booths), hosting live soul/funk 7 nights a week.",
    website: "www.zolaspokane.com"
  },
  {
    id: "lucky-you-lounge-spokane",
    name: "Lucky You Lounge Stage",
    capacity: 320,
    address: "1801 W Sunset Hwy, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Indie Rock", "Americana", "Folk", "Electronic"],
    contactEmail: "booking@luckyyoulounge.com",
    contactPhone: "(509) 474-9055",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 320 guests] Renowned Spokane concert space with spacious dance floor, restaurant, basement cocktail bar, and pristine touring line-array audio.",
    website: "www.luckyyoulounge.com"
  },
  {
    id: "the-pin-spokane",
    name: "The Pin Concert Stage",
    capacity: 200,
    address: "412 W Sprague Ave, Spokane, WA 99201",
    city: "Spokane",
    genres: ["Metal", "Hardcore", "Hip-Hop", "Punk"],
    contactEmail: "thepinspokane@gmail.com",
    contactPhone: "(509) 624-4075",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] High-energy downtown Spokane concert hall and club featuring heavy touring metal, punk, and rap shows with dynamic light rig.",
    website: "www.thepinspokane.com"
  },

  // Central Washington & Columbia Basin
  {
    id: "the-seasons-performance-hall-yakima",
    name: "The Seasons Performance Hall",
    capacity: 250,
    address: "101 N Naches Ave, Yakima, WA 98901",
    city: "Yakima",
    genres: ["Jazz", "Classical", "Folk", "World", "Indie Acoustic"],
    contactEmail: "info@theseasonsyakima.com",
    contactPhone: "(509) 453-1888",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Converted 1917 historic church with cathedral ceilings and stained glass. Celebrated for natural acoustic warmth and Steinway grand piano.",
    website: "www.theseasonsyakima.com"
  },
  {
    id: "single-hill-brewing-yakima",
    name: "Single Hill Brewing Stage",
    capacity: 180,
    address: "102 N Naches Ave, Yakima, WA 98901",
    city: "Yakima",
    genres: ["Indie Rock", "Americana", "Bluegrass", "Folk"],
    contactEmail: "events@singlehillbrewing.com",
    contactPhone: "(509) 367-6770",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Award-winning Yakima taproom with expansive indoor/outdoor community space and regular touring music in the heart of hop country.",
    website: "www.singlehillbrewing.com"
  },
  {
    id: "rays-golden-lion-richland",
    name: "Ray's Golden Lion",
    capacity: 300,
    address: "1353 George Washington Way, Richland, WA 99352",
    city: "Richland",
    genres: ["Punk", "Metal", "Hard Rock", "Indie", "Alternative"],
    contactEmail: "raysgoldenlionevents@gmail.com",
    contactPhone: "(509) 942-8356",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 300 guests] Historic Tri-Cities live music institution with a massive raised stage, loud concert sound system, and storied history hosting national punk and rock acts.",
    website: "www.raysgoldenlion.com"
  },
  {
    id: "emerald-of-siam-richland",
    name: "The Emerald of Siam Thai Restaurant & Lounge",
    capacity: 180,
    address: "704 Jadwin Ave, Richland, WA 99352",
    city: "Richland",
    genres: ["Jazz", "Blues", "Indie Rock", "Funk", "Americana"],
    contactEmail: "emeraldofsiam@gmail.com",
    contactPhone: "(509) 946-9328",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Family-run authentic Thai restaurant in Richland's Uptown Shopping Center, beloved across the Pacific Northwest for hosting live touring bands nearly every night.",
    website: "www.emeraldofsiam.com"
  },
  {
    id: "uptown-theatre-richland",
    name: "The Historic Uptown Theatre",
    capacity: 550,
    address: "1300 Jadwin Ave, Richland, WA 99352",
    city: "Richland",
    genres: ["Rock", "Country", "Tribute", "Indie", "Comedy"],
    contactEmail: "booking@uptowntheatretricities.com",
    contactPhone: "(509) 943-8555",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 550 guests] 1950 Mid-Century theater in the Uptown Richland district, newly equipped for live rock concerts, community festivals, and touring showcases.",
    website: "www.uptowntheatretricities.com"
  },
  {
    id: "outlaw-tavern-pasco",
    name: "The Outlaw Tavern",
    capacity: 200,
    address: "414 W Lewis St, Pasco, WA 99301",
    city: "Pasco",
    genres: ["Country", "Southern Rock", "Americana", "Blues"],
    contactEmail: "outlawtavernbooking@gmail.com",
    contactPhone: "(509) 547-4900",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] High-energy country and rock bar in Pasco with large wooden dance floor, pool tables, and weekend regional live acts.",
    website: "www.facebook.com/theoutlawtavern"
  },
  {
    id: "numerica-pac-wenatchee",
    name: "Numerica Performing Arts Center",
    capacity: 550,
    address: "123 N Wenatchee Ave, Wenatchee, WA 98801",
    city: "Wenatchee",
    genres: ["Classical", "Rock", "Jazz", "Folk", "Theatre"],
    contactEmail: "boxoffice@numericapac.org",
    contactPhone: "(509) 663-2787",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 550 guests] Premier cultural facility in downtown Wenatchee featuring continental seating, fly loft, and top-tier concert audio/lighting systems.",
    website: "www.numericapac.org"
  },
  {
    id: "wallys-house-of-booze-wenatchee",
    name: "Wally's House of Booze",
    capacity: 120,
    address: "214 S Wenatchee Ave, Wenatchee, WA 98801",
    city: "Wenatchee",
    genres: ["Punk", "Metal", "Garage Rock", "Indie"],
    contactEmail: "wallyshouseofbooze@gmail.com",
    contactPhone: "(509) 667-2490",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Wenatchee's premier rock & roll watering hole. Intimate stage, pinball, cold beers, and energetic live shows.",
    website: "www.facebook.com/wallyshouseofbooze"
  },
  {
    id: "old-schoolhouse-brewery-winthrop",
    name: "Old Schoolhouse Brewery & Stage",
    capacity: 180,
    address: "155 Riverside Ave, Winthrop, WA 98862",
    city: "Winthrop",
    genres: ["Bluegrass", "Folk", "Americana", "Rock", "Funk"],
    contactEmail: "info@oldschoolhousebrewery.com",
    contactPhone: "(509) 996-3183",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Award-winning craft brewery along the Chewuch River in the Old West town of Winthrop. Riverside summer deck and cozy winter taproom stage.",
    website: "www.oldschoolhousebrewery.com"
  },
  {
    id: "twisp-river-pub-twisp",
    name: "Twisp River Pub",
    capacity: 160,
    address: "201 Methow Valley Hwy N, Twisp, WA 98856",
    city: "Twisp",
    genres: ["Americana", "Folk Rock", "Blues", "Bluegrass"],
    contactEmail: "music@twispriverpub.com",
    contactPhone: "(509) 997-6822",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 160 guests] Methow Valley live music hub with outdoor riverside lawn stage and cozy indoor woodstove pub for touring acoustic and roots acts.",
    website: "www.twispriverpub.com"
  },
  {
    id: "blue-rock-saloon-ellensburg",
    name: "Blue Rock Saloon",
    capacity: 220,
    address: "409 N Main St, Ellensburg, WA 98926",
    city: "Ellensburg",
    genres: ["Country", "Southern Rock", "Americana", "Cover Rock"],
    contactEmail: "events@bluerocksaloon.com",
    contactPhone: "(509) 962-9099",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] High-energy country and rock venue in downtown Ellensburg near CWU. Massive dance floor, pro sound rig, and lively collegiate weekend crowds.",
    website: "www.bluerocksaloon.com"
  },
  {
    id: "old-red-mill-ellensburg",
    name: "The Old Red Mill Pub & Music Stage",
    capacity: 130,
    address: "207 W 3rd Ave, Ellensburg, WA 98926",
    city: "Ellensburg",
    genres: ["Indie Rock", "Folk", "Blues", "Americana"],
    contactEmail: "redmillellensburg@gmail.com",
    contactPhone: "(509) 925-5000",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Historic downtown Ellensburg pub featuring craft draft lines, brick walls, and intimate weekend live touring band performances.",
    website: "www.facebook.com/oldredmill"
  },
  {
    id: "main-street-ale-house-cle-elum",
    name: "Main Street Ale House Stage",
    capacity: 110,
    address: "313 E 1st St, Cle Elum, WA 98922",
    city: "Cle Elum",
    genres: ["Acoustic", "Folk", "Classic Rock", "Blues"],
    contactEmail: "mainstreetalehouse@gmail.com",
    contactPhone: "(509) 674-2005",
    hasPA: true,
    hasLighting: false,
    description: "[Capacity: 110 guests] Cascade mountain foothills gathering spot offering local Northwest brews and live acoustic sets for travelers on I-90.",
    website: "www.mainstreetalehousecleelum.com"
  },

  // Walla Walla & Palouse
  {
    id: "gesa-power-house-theatre-walla-walla",
    name: "Gesa Power House Theatre",
    capacity: 340,
    address: "111 N 6th Ave, Walla Walla, WA 99362",
    city: "Walla Walla",
    genres: ["Folk", "Classical", "Jazz", "Indie Rock", "Americana"],
    contactEmail: "info@phtww.org",
    contactPhone: "(509) 529-6500",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 340 guests] World-class 1890 power station transformed into an Elizabethan-style theater. Outfitted with state-of-the-art acoustics and lighting in downtown Walla Walla.",
    website: "www.phtww.org"
  },
  {
    id: "main-street-studios-walla-walla",
    name: "Main Street Studios",
    capacity: 250,
    address: "207 W Main St, Walla Walla, WA 99362",
    city: "Walla Walla",
    genres: ["Indie Rock", "Punk", "Funk", "Blues", "Electronic"],
    contactEmail: "booking@mainstreetstudiosww.com",
    contactPhone: "(509) 520-4100",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Downtown Walla Walla independent music and production venue with large wood floor, full lighting rig, and touring band hospitality.",
    website: "www.mainstreetstudiosww.com"
  },
  {
    id: "tranche-estate-walla-walla",
    name: "Tranche Estate Amphitheater",
    capacity: 800,
    address: "705 Berney Dr, Walla Walla, WA 99362",
    city: "Walla Walla",
    genres: ["Americana", "Indie Folk", "Soul", "Blues", "Jazz"],
    contactEmail: "music@tranche.wine",
    contactPhone: "(509) 526-3500",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 800 guests] Stunning outdoor winery concert pavilion nestled in the Blue Mountain foothills with lawn seating, wine bar, and food truck corrals.",
    website: "www.tranche.wine"
  },
  {
    id: "ricos-public-house-pullman",
    name: "Rico's Public House",
    capacity: 150,
    address: "200 E Main St, Pullman, WA 99163",
    city: "Pullman",
    genres: ["Jazz", "Folk", "Indie Rock", "Blues", "Americana"],
    contactEmail: "booking@ricoscorner.com",
    contactPhone: "(509) 332-6566",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Pullman's historic 1909 brick gathering place in the heart of WSU Palouse country. Famous for live jazz, open mic traditions, and craft beers.",
    website: "www.ricoscorner.com"
  },
  {
    id: "etsi-bravo-pullman",
    name: "Etsi Bravo",
    capacity: 180,
    address: "215 E Main St 2nd Floor, Pullman, WA 99163",
    city: "Pullman",
    genres: ["Indie", "Electronic", "Hip-Hop", "Funk", "House"],
    contactEmail: "booking@etsibravo.com",
    contactPhone: "(509) 339-6535",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Second-story speakeasy nightclub and live lounge in downtown Pullman with plush booth seating, craft cocktails, and high-end sound.",
    website: "www.etsibravo.com"
  },

  // SW Washington
  {
    id: "six-shooter-bar-vancouver",
    name: "Six Shooter Bar",
    capacity: 120,
    address: "6115 NE St Johns Rd, Vancouver, WA 98661",
    city: "Vancouver",
    genres: ["Punk", "Outlaw Country", "Rockabilly", "Metal"],
    contactEmail: "sixshootervanwa@gmail.com",
    contactPhone: "(360) 906-8964",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 120 guests] Gritty rock & roll hangout in Vancouver with dedicated live stage, cold craft pints, and welcoming DIY spirit.",
    website: "www.facebook.com/sixshooterbar"
  },
  {
    id: "underbar-vancouver",
    name: "UnderBar",
    capacity: 90,
    address: "1701 1/2 Broadway St, Vancouver, WA 98663",
    city: "Vancouver",
    genres: ["Indie Rock", "Jazz", "Acoustic", "Blues", "Cabaret"],
    contactEmail: "underbarvancouver@gmail.com",
    contactPhone: "(360) 258-1146",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 90 guests] Subterranean speakeasy bar in downtown Vancouver featuring craft cocktails, vinyl sessions, and live acoustic music.",
    website: "www.underbar.pub"
  },
  {
    id: "brickhouse-bar-vancouver",
    name: "Brickhouse Bar & Grill",
    capacity: 180,
    address: "109 W 15th St, Vancouver, WA 98660",
    city: "Vancouver",
    genres: ["Blues", "Funk", "Rock", "Americana", "Reggae"],
    contactEmail: "brickhousevancouver@gmail.com",
    contactPhone: "(360) 695-3686",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Downtown Vancouver institution featuring 24 craft beer taps, outdoor heated patio, and live music every weekend on the brick stage.",
    website: "www.vancouverbrickhouse.com"
  },
  {
    id: "kiggins-theatre-vancouver",
    name: "Kiggins Theatre",
    capacity: 340,
    address: "1111 Main St, Vancouver, WA 98660",
    city: "Vancouver",
    genres: ["Indie", "Folk", "Film", "Jazz", "Comedy"],
    contactEmail: "events@kigginstheatre.net",
    contactPhone: "(360) 816-0352",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 340 guests] Historic 1936 single-screen Art Deco cinema and performing arts theater on Main Street in downtown Vancouver.",
    website: "www.kigginstheatre.com"
  },
  {
    id: "electric-cheetah-longview",
    name: "The Electric Cheetah",
    capacity: 150,
    address: "1333 Commerce Ave, Longview, WA 98632",
    city: "Longview",
    genres: ["Punk", "Metal", "Alternative", "Garage Rock"],
    contactEmail: "electriccheetahlongview@gmail.com",
    contactPhone: "(360) 425-9988",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 150 guests] Downtown Longview underground live music and gaming lounge supporting local and touring alternative acts on the I-5 corridor.",
    website: "www.facebook.com/electriccheetah"
  },
  {
    id: "olympic-club-theater-centralia",
    name: "McMenamins Olympic Club Theater",
    capacity: 220,
    address: "112 N Tower Ave, Centralia, WA 98531",
    city: "Centralia",
    genres: ["Americana", "Bluegrass", "Indie Rock", "Folk", "Blues"],
    contactEmail: "booking@mcmenamins.com",
    contactPhone: "(360) 736-5164",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 220 guests] Historic 1908 railroad saloon and hotel theater in downtown Centralia. Vintage couches, handcrafted ales, and midway tour stop convenience.",
    website: "www.mcmenamins.com/olympic-club"
  },
  {
    id: "the-juice-box-centralia",
    name: "The Juice Box Public House",
    capacity: 130,
    address: "216 S Tower Ave, Centralia, WA 98531",
    city: "Centralia",
    genres: ["Indie Rock", "Americana", "Folk", "Punk"],
    contactEmail: "thejuiceboxcentralia@gmail.com",
    contactPhone: "(360) 807-4387",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 130 guests] Community-centered downtown Centralia taproom and venue featuring regional Northwest cider and beer, local art, and live music.",
    website: "www.thejuiceboxpublichouse.com"
  },
  {
    id: "mcfilers-chehalis",
    name: "McFiler's",
    capacity: 140,
    address: "543 NW Pacific Ave, Chehalis, WA 98532",
    city: "Chehalis",
    genres: ["Rock", "Punk", "Blues", "Americana", "Country"],
    contactEmail: "mcfilerschehalis@gmail.com",
    contactPhone: "(360) 996-4400",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 140 guests] Lively downtown Chehalis bar & grill with energetic weekend bands, patio seating, and full stage lighting/audio.",
    website: "www.mcfilers.com"
  },
  {
    id: "walking-man-brewing-stevenson",
    name: "Walking Man Brewing - Grain Room & Beer Garden",
    capacity: 180,
    address: "240 SW 1st St, Stevenson, WA 98648",
    city: "Stevenson",
    genres: ["Bluegrass", "Americana", "Indie Folk", "Blues"],
    contactEmail: "info@walkingmanbeer.com",
    contactPhone: "(509) 427-5520",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 180 guests] Pioneer Columbia River Gorge craft brewery featuring outdoor forested beer garden stage with views of Cascade cliffs.",
    website: "www.walkingmanbeer.com"
  },
  {
    id: "the-society-hotel-bingen",
    name: "The Society Hotel Bingen Gymnasium Stage",
    capacity: 250,
    address: "210 Cedar St, Bingen, WA 98605",
    city: "Bingen",
    genres: ["Indie Folk", "Acoustic", "Ambient", "Americana"],
    contactEmail: "events@thesocietyhotel.com",
    contactPhone: "(509) 774-4437",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 250 guests] Restored 1930s schoolhouse gymnasium in Bingen, WA across from Hood River. Warm wood acoustic reverberation and lodging on-site for touring artists.",
    website: "www.thesocietyhotel.com/bingen"
  },
  {
    id: "friday-harbor-brickworks",
    name: "Brickworks Events Center",
    capacity: 200,
    address: "150 Nichols St, Friday Harbor, WA 98250",
    city: "Friday Harbor",
    genres: ["Folk", "Americana", "Indie Rock", "World"],
    contactEmail: "brickworks@fhbrickworks.org",
    contactPhone: "(360) 378-0095",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 200 guests] San Juan Island historic brick and fir timber event hall steps from the ferry terminal. Superb island tour destination.",
    website: "www.fhbrickworks.org"
  },
  {
    id: "san-juan-community-theatre",
    name: "San Juan Community Theatre - Whittier Stage",
    capacity: 280,
    address: "100 2nd St N, Friday Harbor, WA 98250",
    city: "Friday Harbor",
    genres: ["Classical", "Jazz", "Folk", "Chamber", "World"],
    contactEmail: "info@sjctheatre.org",
    contactPhone: "(360) 378-3210",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 280 guests] Beautiful island performing arts complex featuring full theatrical rigging and acoustic orchestra shell.",
    website: "www.sjctheatre.org"
  },
  {
    id: "aberdeen-d&r-theatre",
    name: "D&R Theatre",
    capacity: 950,
    address: "205 S I St, Aberdeen, WA 98520",
    city: "Aberdeen",
    genres: ["Grunge", "Rock", "Metal", "Tribute", "Indie"],
    contactEmail: "booking@drtheatre.com",
    contactPhone: "(360) 537-0400",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 950 guests] Historic 1924 theater in the hometown of Kurt Cobain / Nirvana. Grand Art Deco proscenium with modern concert sound array.",
    website: "www.drtheatre.com"
  },
  {
    id: "hoquiam-7th-street-theatre",
    name: "7th Street Theatre",
    capacity: 900,
    address: "313 7th St, Hoquiam, WA 98550",
    city: "Hoquiam",
    genres: ["Classic Rock", "Folk", "Blues", "Americana"],
    contactEmail: "events@7thstreettheatre.com",
    contactPhone: "(360) 532-5960",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 900 guests] Washington's only remaining atmospheric theater, featuring a painted starry cloud ceiling and Spanish castle facade.",
    website: "www.7thstreettheatre.com"
  },
  {
    id: "vashon-center-for-arts",
    name: "Vashon Center for the Arts - Kay White Hall",
    capacity: 300,
    address: "19600 Vashon Hwy SW, Vashon, WA 98070",
    city: "Vashon",
    genres: ["Jazz", "Folk", "Classical", "Indie Rock", "World"],
    contactEmail: "info@vashoncenterforthearts.org",
    contactPhone: "(206) 463-5131",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 300 guests] World-class island concert hall featuring adjustable acoustic banners, state-of-the-art lighting, and island tour hospitality.",
    website: "www.vashoncenterforthearts.org"
  },
  {
    id: "bainbridge-performing-arts",
    name: "Bainbridge Performing Arts (Buxton Center)",
    capacity: 245,
    address: "200 Madison Ave N, Bainbridge Island, WA 98110",
    city: "Bainbridge Island",
    genres: ["Jazz", "Classical", "Indie", "Folk", "Theatre"],
    contactEmail: "info@bainbridgeperformingarts.org",
    contactPhone: "(206) 842-8569",
    hasPA: true,
    hasLighting: true,
    description: "[Capacity: 245 guests] Brand-new state-of-the-art performance hall steps from Winslow Way and the Seattle-Bainbridge ferry.",
    website: "www.bainbridgeperformingarts.org"
  }
];

console.log('Generating Oregon and Washington datasets...');
